name: mailslurp
targets:
  mailslurp:
    type: framework
    platform: iOS
    deploymentTarget: "10.0"
    sources: [mailslurp]
    info:
      path: ./Info.plist
      version: 8.2.5
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    
