name: mailslurp
targets:
  mailslurp:
    type: framework
    platform: iOS
    deploymentTarget: "9.0"
    sources: [mailslurp]
    info:
      path: ./Info.plist
      version: 15.7.17
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
    - carthage: PromiseKit
    - carthage: AnyCodable
