//
// MailServerControllerAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



@objc open class MailServerControllerAPI : NSObject {
    /**
     Get DNS Mail Server records for a domain
     
     - parameter describeOptions: (body) describeOptions 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func describeMailServerDomain(describeOptions: DescribeDomainOptions, apiResponseQueue: DispatchQueue = mailslurpAPI.apiResponseQueue, completion: @escaping ((_ data: DescribeMailServerDomainResult?,_ error: Error?) -> Void)) {
        describeMailServerDomainWithRequestBuilder(describeOptions: describeOptions).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get DNS Mail Server records for a domain
     - POST /mail-server/describe/domain
     - API Key:
       - type: apiKey x-api-key 
       - name: API_KEY
     - parameter describeOptions: (body) describeOptions 
     - returns: RequestBuilder<DescribeMailServerDomainResult> 
     */
    open class func describeMailServerDomainWithRequestBuilder(describeOptions: DescribeDomainOptions) -> RequestBuilder<DescribeMailServerDomainResult> {
        let path = "/mail-server/describe/domain"
        let URLString = mailslurpAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: describeOptions)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<DescribeMailServerDomainResult>.Type = mailslurpAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**
     Lookup DNS records for a domain
     
     - parameter dnsLookupOptions: (body) dnsLookupOptions 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getDnsLookup(dnsLookupOptions: DNSLookupOptions, apiResponseQueue: DispatchQueue = mailslurpAPI.apiResponseQueue, completion: @escaping ((_ data: DNSLookupResults?,_ error: Error?) -> Void)) {
        getDnsLookupWithRequestBuilder(dnsLookupOptions: dnsLookupOptions).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Lookup DNS records for a domain
     - POST /mail-server/describe/dns-lookup
     - API Key:
       - type: apiKey x-api-key 
       - name: API_KEY
     - parameter dnsLookupOptions: (body) dnsLookupOptions 
     - returns: RequestBuilder<DNSLookupResults> 
     */
    open class func getDnsLookupWithRequestBuilder(dnsLookupOptions: DNSLookupOptions) -> RequestBuilder<DNSLookupResults> {
        let path = "/mail-server/describe/dns-lookup"
        let URLString = mailslurpAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: dnsLookupOptions)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<DNSLookupResults>.Type = mailslurpAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**
     Get IP address for a domain
     
     - parameter name: (query) name 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getIpAddress(name: String, apiResponseQueue: DispatchQueue = mailslurpAPI.apiResponseQueue, completion: @escaping ((_ data: IPAddressResult?,_ error: Error?) -> Void)) {
        getIpAddressWithRequestBuilder(name: name).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get IP address for a domain
     - POST /mail-server/describe/ip-address
     - API Key:
       - type: apiKey x-api-key 
       - name: API_KEY
     - parameter name: (query) name 
     - returns: RequestBuilder<IPAddressResult> 
     */
    open class func getIpAddressWithRequestBuilder(name: String) -> RequestBuilder<IPAddressResult> {
        let path = "/mail-server/describe/ip-address"
        let URLString = mailslurpAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "name": name.encodeToJSON()
        ])

        let requestBuilder: RequestBuilder<IPAddressResult>.Type = mailslurpAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Verify the existence of an email address at a given mail server.
     
     - parameter verifyOptions: (body) verifyOptions 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func verifyEmailAddress(verifyOptions: VerifyEmailAddressOptions, apiResponseQueue: DispatchQueue = mailslurpAPI.apiResponseQueue, completion: @escaping ((_ data: EmailVerificationResult?,_ error: Error?) -> Void)) {
        verifyEmailAddressWithRequestBuilder(verifyOptions: verifyOptions).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Verify the existence of an email address at a given mail server.
     - POST /mail-server/verify/email-address
     - API Key:
       - type: apiKey x-api-key 
       - name: API_KEY
     - parameter verifyOptions: (body) verifyOptions 
     - returns: RequestBuilder<EmailVerificationResult> 
     */
    open class func verifyEmailAddressWithRequestBuilder(verifyOptions: VerifyEmailAddressOptions) -> RequestBuilder<EmailVerificationResult> {
        let path = "/mail-server/verify/email-address"
        let URLString = mailslurpAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: verifyOptions)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<EmailVerificationResult>.Type = mailslurpAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

}
