//
// WaitForControllerAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



@objc open class WaitForControllerAPI : NSObject {
    /**
     Wait for conditions to be met
     
     - parameter waitForConditions: (body) Conditions to wait for (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func waitFor(waitForConditions: WaitForConditions? = nil, apiResponseQueue: DispatchQueue = mailslurpAPI.apiResponseQueue, completion: @escaping ((_ data: [EmailPreview]?,_ error: Error?) -> Void)) {
        waitForWithRequestBuilder(waitForConditions: waitForConditions).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Wait for conditions to be met
     - POST /waitFor
     - Generic waitFor method that will wait until an inbox meets given conditions or return immediately if already met
     - API Key:
       - type: apiKey x-api-key 
       - name: API_KEY
     - parameter waitForConditions: (body) Conditions to wait for (optional)
     - returns: RequestBuilder<[EmailPreview]> 
     */
    open class func waitForWithRequestBuilder(waitForConditions: WaitForConditions? = nil) -> RequestBuilder<[EmailPreview]> {
        let path = "/waitFor"
        let URLString = mailslurpAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: waitForConditions)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<[EmailPreview]>.Type = mailslurpAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**
     Wait for and return count number of emails 
     
     - parameter count: (query) Number of emails to wait for. Must be greater that 1 (optional)
     - parameter inboxId: (query) Id of the inbox we are fetching emails from (optional)
     - parameter timeout: (query) Max milliseconds to wait (optional)
     - parameter unreadOnly: (query) Optional filter for unread only (optional, default to false)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func waitForEmailCount(count: Int? = nil, inboxId: UUID? = nil, timeout: Int64? = nil, unreadOnly: Bool? = nil, apiResponseQueue: DispatchQueue = mailslurpAPI.apiResponseQueue, completion: @escaping ((_ data: [EmailPreview]?,_ error: Error?) -> Void)) {
        waitForEmailCountWithRequestBuilder(count: count, inboxId: inboxId, timeout: timeout, unreadOnly: unreadOnly).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Wait for and return count number of emails 
     - GET /waitForEmailCount
     - If inbox contains count or more emails at time of request then return count worth of emails. If not wait until the count is reached and return those or return an error if timeout is exceeded.
     - API Key:
       - type: apiKey x-api-key 
       - name: API_KEY
     - parameter count: (query) Number of emails to wait for. Must be greater that 1 (optional)
     - parameter inboxId: (query) Id of the inbox we are fetching emails from (optional)
     - parameter timeout: (query) Max milliseconds to wait (optional)
     - parameter unreadOnly: (query) Optional filter for unread only (optional, default to false)
     - returns: RequestBuilder<[EmailPreview]> 
     */
    open class func waitForEmailCountWithRequestBuilder(count: Int? = nil, inboxId: UUID? = nil, timeout: Int64? = nil, unreadOnly: Bool? = nil) -> RequestBuilder<[EmailPreview]> {
        let path = "/waitForEmailCount"
        let URLString = mailslurpAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "count": count?.encodeToJSON(), 
            "inboxId": inboxId?.encodeToJSON(), 
            "timeout": timeout?.encodeToJSON(), 
            "unreadOnly": unreadOnly?.encodeToJSON()
        ])

        let requestBuilder: RequestBuilder<[EmailPreview]>.Type = mailslurpAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Fetch inbox's latest email or if empty wait for an email to arrive
     
     - parameter inboxId: (query) Id of the inbox we are fetching emails from (optional)
     - parameter timeout: (query) Max milliseconds to wait (optional)
     - parameter unreadOnly: (query) Optional filter for unread only. (optional, default to false)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func waitForLatestEmail(inboxId: UUID? = nil, timeout: Int64? = nil, unreadOnly: Bool? = nil, apiResponseQueue: DispatchQueue = mailslurpAPI.apiResponseQueue, completion: @escaping ((_ data: Email?,_ error: Error?) -> Void)) {
        waitForLatestEmailWithRequestBuilder(inboxId: inboxId, timeout: timeout, unreadOnly: unreadOnly).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Fetch inbox's latest email or if empty wait for an email to arrive
     - GET /waitForLatestEmail
     - Will return either the last received email or wait for an email to arrive and return that. If you need to wait for an email for a non-empty inbox set `unreadOnly=true` or see the other receive methods such as `waitForNthEmail` or `waitForEmailCount`.
     - API Key:
       - type: apiKey x-api-key 
       - name: API_KEY
     - parameter inboxId: (query) Id of the inbox we are fetching emails from (optional)
     - parameter timeout: (query) Max milliseconds to wait (optional)
     - parameter unreadOnly: (query) Optional filter for unread only. (optional, default to false)
     - returns: RequestBuilder<Email> 
     */
    open class func waitForLatestEmailWithRequestBuilder(inboxId: UUID? = nil, timeout: Int64? = nil, unreadOnly: Bool? = nil) -> RequestBuilder<Email> {
        let path = "/waitForLatestEmail"
        let URLString = mailslurpAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "inboxId": inboxId?.encodeToJSON(), 
            "timeout": timeout?.encodeToJSON(), 
            "unreadOnly": unreadOnly?.encodeToJSON()
        ])

        let requestBuilder: RequestBuilder<Email>.Type = mailslurpAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Wait or return list of emails that match simple matching patterns
     
     - parameter matchOptions: (body) matchOptions 
     - parameter count: (query) Number of emails to wait for. Must be greater that 1 (optional)
     - parameter inboxId: (query) Id of the inbox we are fetching emails from (optional)
     - parameter timeout: (query) Max milliseconds to wait (optional)
     - parameter unreadOnly: (query) Optional filter for unread only (optional, default to false)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func waitForMatchingEmail(matchOptions: MatchOptions, count: Int? = nil, inboxId: UUID? = nil, timeout: Int64? = nil, unreadOnly: Bool? = nil, apiResponseQueue: DispatchQueue = mailslurpAPI.apiResponseQueue, completion: @escaping ((_ data: [EmailPreview]?,_ error: Error?) -> Void)) {
        waitForMatchingEmailWithRequestBuilder(matchOptions: matchOptions, count: count, inboxId: inboxId, timeout: timeout, unreadOnly: unreadOnly).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Wait or return list of emails that match simple matching patterns
     - POST /waitForMatchingEmails
     - Perform a search of emails in an inbox with the given patterns. If results match expected count then return or else retry the search until results are found or timeout is reached. Match options allow simple CONTAINS or EQUALS filtering on SUBJECT, TO, BCC, CC, and FROM. See the `MatchOptions` object for options.
     - API Key:
       - type: apiKey x-api-key 
       - name: API_KEY
     - parameter matchOptions: (body) matchOptions 
     - parameter count: (query) Number of emails to wait for. Must be greater that 1 (optional)
     - parameter inboxId: (query) Id of the inbox we are fetching emails from (optional)
     - parameter timeout: (query) Max milliseconds to wait (optional)
     - parameter unreadOnly: (query) Optional filter for unread only (optional, default to false)
     - returns: RequestBuilder<[EmailPreview]> 
     */
    open class func waitForMatchingEmailWithRequestBuilder(matchOptions: MatchOptions, count: Int? = nil, inboxId: UUID? = nil, timeout: Int64? = nil, unreadOnly: Bool? = nil) -> RequestBuilder<[EmailPreview]> {
        let path = "/waitForMatchingEmails"
        let URLString = mailslurpAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: matchOptions)

        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "count": count?.encodeToJSON(), 
            "inboxId": inboxId?.encodeToJSON(), 
            "timeout": timeout?.encodeToJSON(), 
            "unreadOnly": unreadOnly?.encodeToJSON()
        ])

        let requestBuilder: RequestBuilder<[EmailPreview]>.Type = mailslurpAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**
     Wait for or fetch the email with a given index in the inbox specified
     
     - parameter inboxId: (query) Id of the inbox you are fetching emails from (optional)
     - parameter index: (query) Zero based index of the email to wait for. If an inbox has 1 email already and you want to wait for the 2nd email pass index&#x3D;1 (optional, default to 0)
     - parameter timeout: (query) Max milliseconds to wait for the nth email if not already present (optional)
     - parameter unreadOnly: (query) Optional filter for unread only (optional, default to false)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func waitForNthEmail(inboxId: UUID? = nil, index: Int? = nil, timeout: Int64? = nil, unreadOnly: Bool? = nil, apiResponseQueue: DispatchQueue = mailslurpAPI.apiResponseQueue, completion: @escaping ((_ data: Email?,_ error: Error?) -> Void)) {
        waitForNthEmailWithRequestBuilder(inboxId: inboxId, index: index, timeout: timeout, unreadOnly: unreadOnly).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Wait for or fetch the email with a given index in the inbox specified
     - GET /waitForNthEmail
     - If nth email is already present in inbox then return it. If not hold the connection open until timeout expires or the nth email is received and returned.
     - API Key:
       - type: apiKey x-api-key 
       - name: API_KEY
     - parameter inboxId: (query) Id of the inbox you are fetching emails from (optional)
     - parameter index: (query) Zero based index of the email to wait for. If an inbox has 1 email already and you want to wait for the 2nd email pass index&#x3D;1 (optional, default to 0)
     - parameter timeout: (query) Max milliseconds to wait for the nth email if not already present (optional)
     - parameter unreadOnly: (query) Optional filter for unread only (optional, default to false)
     - returns: RequestBuilder<Email> 
     */
    open class func waitForNthEmailWithRequestBuilder(inboxId: UUID? = nil, index: Int? = nil, timeout: Int64? = nil, unreadOnly: Bool? = nil) -> RequestBuilder<Email> {
        let path = "/waitForNthEmail"
        let URLString = mailslurpAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "inboxId": inboxId?.encodeToJSON(), 
            "index": index?.encodeToJSON(), 
            "timeout": timeout?.encodeToJSON(), 
            "unreadOnly": unreadOnly?.encodeToJSON()
        ])

        let requestBuilder: RequestBuilder<Email>.Type = mailslurpAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
