//
// WebhookControllerAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import PromiseKit

@objc open class WebhookControllerAPI : NSObject {
    /**
     Attach a WebHook URL to an inbox
     
     - parameter createWebhookOptions: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: Promise<WebhookDto>
     */
    open class func createAccountWebhook( createWebhookOptions: CreateWebhookOptions, apiResponseQueue: DispatchQueue = mailslurpAPI.apiResponseQueue) -> Promise<WebhookDto> {
        let deferred = Promise<WebhookDto>.pending()
        createAccountWebhookWithRequestBuilder(createWebhookOptions: createWebhookOptions).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                deferred.resolver.fulfill(response.body!)
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     Attach a WebHook URL to an inbox
     - POST /webhooks
     - Get notified of account level events such as bounce and bounce recipient.
     - API Key:
       - type: apiKey x-api-key 
       - name: API_KEY
     - parameter createWebhookOptions: (body)  
     - returns: RequestBuilder<WebhookDto> 
     */
    open class func createAccountWebhookWithRequestBuilder(createWebhookOptions: CreateWebhookOptions) -> RequestBuilder<WebhookDto> {
        let path = "/webhooks"
        let URLString = mailslurpAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createWebhookOptions)

        let urlComponents = URLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<WebhookDto>.Type = mailslurpAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**
     Attach a WebHook URL to an inbox
     
     - parameter inboxId: (path)  
     - parameter createWebhookOptions: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: Promise<WebhookDto>
     */
    open class func createWebhook( inboxId: UUID,  createWebhookOptions: CreateWebhookOptions, apiResponseQueue: DispatchQueue = mailslurpAPI.apiResponseQueue) -> Promise<WebhookDto> {
        let deferred = Promise<WebhookDto>.pending()
        createWebhookWithRequestBuilder(inboxId: inboxId, createWebhookOptions: createWebhookOptions).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                deferred.resolver.fulfill(response.body!)
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     Attach a WebHook URL to an inbox
     - POST /inboxes/{inboxId}/webhooks
     - Get notified whenever an inbox receives an email via a WebHook URL. An emailID will be posted to this URL every time an email is received for this inbox. The URL must be publicly reachable by the MailSlurp server. You can provide basicAuth values if you wish to secure this endpoint.
     - API Key:
       - type: apiKey x-api-key 
       - name: API_KEY
     - parameter inboxId: (path)  
     - parameter createWebhookOptions: (body)  
     - returns: RequestBuilder<WebhookDto> 
     */
    open class func createWebhookWithRequestBuilder(inboxId: UUID, createWebhookOptions: CreateWebhookOptions) -> RequestBuilder<WebhookDto> {
        var path = "/inboxes/{inboxId}/webhooks"
        let inboxIdPreEscape = "\(APIHelper.mapValueToPathItem(inboxId))"
        let inboxIdPostEscape = inboxIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{inboxId}", with: inboxIdPostEscape, options: .literal, range: nil)
        let URLString = mailslurpAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createWebhookOptions)

        let urlComponents = URLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<WebhookDto>.Type = mailslurpAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**
     Delete all webhooks
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: Promise<Void>
     */
    open class func deleteAllWebhooks(apiResponseQueue: DispatchQueue = mailslurpAPI.apiResponseQueue) -> Promise<Void> {
        let deferred = Promise<Void>.pending()
        deleteAllWebhooksWithRequestBuilder().execute(apiResponseQueue) { result -> Void in
            switch result {
            case .success:
                deferred.resolver.fulfill(())
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     Delete all webhooks
     - DELETE /webhooks
     - API Key:
       - type: apiKey x-api-key 
       - name: API_KEY
     - returns: RequestBuilder<Void> 
     */
    open class func deleteAllWebhooksWithRequestBuilder() -> RequestBuilder<Void> {
        let path = "/webhooks"
        let URLString = mailslurpAPI.basePath + path
        let parameters: [String: Any]? = nil

        let urlComponents = URLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = mailslurpAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**
     Delete and disable a Webhook for an Inbox
     
     - parameter inboxId: (path)  
     - parameter webhookId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: Promise<Void>
     */
    open class func deleteWebhook( inboxId: UUID,  webhookId: UUID, apiResponseQueue: DispatchQueue = mailslurpAPI.apiResponseQueue) -> Promise<Void> {
        let deferred = Promise<Void>.pending()
        deleteWebhookWithRequestBuilder(inboxId: inboxId, webhookId: webhookId).execute(apiResponseQueue) { result -> Void in
            switch result {
            case .success:
                deferred.resolver.fulfill(())
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     Delete and disable a Webhook for an Inbox
     - DELETE /inboxes/{inboxId}/webhooks/{webhookId}
     - API Key:
       - type: apiKey x-api-key 
       - name: API_KEY
     - parameter inboxId: (path)  
     - parameter webhookId: (path)  
     - returns: RequestBuilder<Void> 
     */
    open class func deleteWebhookWithRequestBuilder(inboxId: UUID, webhookId: UUID) -> RequestBuilder<Void> {
        var path = "/inboxes/{inboxId}/webhooks/{webhookId}"
        let inboxIdPreEscape = "\(APIHelper.mapValueToPathItem(inboxId))"
        let inboxIdPostEscape = inboxIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{inboxId}", with: inboxIdPostEscape, options: .literal, range: nil)
        let webhookIdPreEscape = "\(APIHelper.mapValueToPathItem(webhookId))"
        let webhookIdPostEscape = webhookIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{webhookId}", with: webhookIdPostEscape, options: .literal, range: nil)
        let URLString = mailslurpAPI.basePath + path
        let parameters: [String: Any]? = nil

        let urlComponents = URLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = mailslurpAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**
     Delete a webhook
     
     - parameter webhookId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: Promise<Void>
     */
    open class func deleteWebhookById( webhookId: UUID, apiResponseQueue: DispatchQueue = mailslurpAPI.apiResponseQueue) -> Promise<Void> {
        let deferred = Promise<Void>.pending()
        deleteWebhookByIdWithRequestBuilder(webhookId: webhookId).execute(apiResponseQueue) { result -> Void in
            switch result {
            case .success:
                deferred.resolver.fulfill(())
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     Delete a webhook
     - DELETE /webhooks/{webhookId}
     - API Key:
       - type: apiKey x-api-key 
       - name: API_KEY
     - parameter webhookId: (path)  
     - returns: RequestBuilder<Void> 
     */
    open class func deleteWebhookByIdWithRequestBuilder(webhookId: UUID) -> RequestBuilder<Void> {
        var path = "/webhooks/{webhookId}"
        let webhookIdPreEscape = "\(APIHelper.mapValueToPathItem(webhookId))"
        let webhookIdPostEscape = webhookIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{webhookId}", with: webhookIdPostEscape, options: .literal, range: nil)
        let URLString = mailslurpAPI.basePath + path
        let parameters: [String: Any]? = nil

        let urlComponents = URLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = mailslurpAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**
     * enum for parameter sort
     */
    public enum Sort_getAllWebhookResults: String, CaseIterable {
        case asc = "ASC"
        case desc = "DESC"
    }

    /**
     Get results for all webhooks
     
     - parameter page: (query) Optional page index in list pagination (optional, default to 0)
     - parameter size: (query) Optional page size in list pagination (optional, default to 20)
     - parameter sort: (query) Optional createdAt sort direction ASC or DESC (optional, default to .asc)
     - parameter searchFilter: (query) Optional search filter (optional)
     - parameter since: (query) Filter by created at after the given timestamp (optional)
     - parameter before: (query) Filter by created at before the given timestamp (optional)
     - parameter unseenOnly: (query) Filter for unseen exceptions only (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: Promise<PageWebhookResult>
     */
    open class func getAllWebhookResults( page: Int? = nil,  size: Int? = nil,  sort: Sort_getAllWebhookResults? = nil,  searchFilter: String? = nil,  since: Date? = nil,  before: Date? = nil,  unseenOnly: Bool? = nil, apiResponseQueue: DispatchQueue = mailslurpAPI.apiResponseQueue) -> Promise<PageWebhookResult> {
        let deferred = Promise<PageWebhookResult>.pending()
        getAllWebhookResultsWithRequestBuilder(page: page, size: size, sort: sort, searchFilter: searchFilter, since: since, before: before, unseenOnly: unseenOnly).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                deferred.resolver.fulfill(response.body!)
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     Get results for all webhooks
     - GET /webhooks/results
     - API Key:
       - type: apiKey x-api-key 
       - name: API_KEY
     - parameter page: (query) Optional page index in list pagination (optional, default to 0)
     - parameter size: (query) Optional page size in list pagination (optional, default to 20)
     - parameter sort: (query) Optional createdAt sort direction ASC or DESC (optional, default to .asc)
     - parameter searchFilter: (query) Optional search filter (optional)
     - parameter since: (query) Filter by created at after the given timestamp (optional)
     - parameter before: (query) Filter by created at before the given timestamp (optional)
     - parameter unseenOnly: (query) Filter for unseen exceptions only (optional)
     - returns: RequestBuilder<PageWebhookResult> 
     */
    open class func getAllWebhookResultsWithRequestBuilder(page: Int? = nil, size: Int? = nil, sort: Sort_getAllWebhookResults? = nil, searchFilter: String? = nil, since: Date? = nil, before: Date? = nil, unseenOnly: Bool? = nil) -> RequestBuilder<PageWebhookResult> {
        let path = "/webhooks/results"
        let URLString = mailslurpAPI.basePath + path
        let parameters: [String: Any]? = nil

        var urlComponents = URLComponents(string: URLString)
        urlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "page": page?.encodeToJSON(),
            "size": size?.encodeToJSON(),
            "sort": sort?.encodeToJSON(),
            "searchFilter": searchFilter?.encodeToJSON(),
            "since": since?.encodeToJSON(),
            "before": before?.encodeToJSON(),
            "unseenOnly": unseenOnly?.encodeToJSON(),
        ])

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<PageWebhookResult>.Type = mailslurpAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**
     * enum for parameter sort
     */
    public enum Sort_getAllWebhooks: String, CaseIterable {
        case asc = "ASC"
        case desc = "DESC"
    }

    /**
     List Webhooks Paginated
     
     - parameter page: (query) Optional page index in list pagination (optional, default to 0)
     - parameter size: (query) Optional page size for paginated result list. (optional, default to 20)
     - parameter sort: (query) Optional createdAt sort direction ASC or DESC (optional, default to .desc)
     - parameter searchFilter: (query) Optional search filter (optional)
     - parameter since: (query) Filter by created at after the given timestamp (optional)
     - parameter before: (query) Filter by created at before the given timestamp (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: Promise<PageWebhookProjection>
     */
    open class func getAllWebhooks( page: Int? = nil,  size: Int? = nil,  sort: Sort_getAllWebhooks? = nil,  searchFilter: String? = nil,  since: Date? = nil,  before: Date? = nil, apiResponseQueue: DispatchQueue = mailslurpAPI.apiResponseQueue) -> Promise<PageWebhookProjection> {
        let deferred = Promise<PageWebhookProjection>.pending()
        getAllWebhooksWithRequestBuilder(page: page, size: size, sort: sort, searchFilter: searchFilter, since: since, before: before).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                deferred.resolver.fulfill(response.body!)
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     List Webhooks Paginated
     - GET /webhooks/paginated
     - List webhooks in paginated form. Allows for page index, page size, and sort direction.
     - API Key:
       - type: apiKey x-api-key 
       - name: API_KEY
     - parameter page: (query) Optional page index in list pagination (optional, default to 0)
     - parameter size: (query) Optional page size for paginated result list. (optional, default to 20)
     - parameter sort: (query) Optional createdAt sort direction ASC or DESC (optional, default to .desc)
     - parameter searchFilter: (query) Optional search filter (optional)
     - parameter since: (query) Filter by created at after the given timestamp (optional)
     - parameter before: (query) Filter by created at before the given timestamp (optional)
     - returns: RequestBuilder<PageWebhookProjection> 
     */
    open class func getAllWebhooksWithRequestBuilder(page: Int? = nil, size: Int? = nil, sort: Sort_getAllWebhooks? = nil, searchFilter: String? = nil, since: Date? = nil, before: Date? = nil) -> RequestBuilder<PageWebhookProjection> {
        let path = "/webhooks/paginated"
        let URLString = mailslurpAPI.basePath + path
        let parameters: [String: Any]? = nil

        var urlComponents = URLComponents(string: URLString)
        urlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "page": page?.encodeToJSON(),
            "size": size?.encodeToJSON(),
            "sort": sort?.encodeToJSON(),
            "searchFilter": searchFilter?.encodeToJSON(),
            "since": since?.encodeToJSON(),
            "before": before?.encodeToJSON(),
        ])

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<PageWebhookProjection>.Type = mailslurpAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**
     * enum for parameter sort
     */
    public enum Sort_getInboxWebhooksPaginated: String, CaseIterable {
        case asc = "ASC"
        case desc = "DESC"
    }

    /**
     Get paginated webhooks for an Inbox
     
     - parameter inboxId: (path)  
     - parameter page: (query) Optional page index in list pagination (optional, default to 0)
     - parameter size: (query) Optional page size in list pagination (optional, default to 20)
     - parameter sort: (query) Optional createdAt sort direction ASC or DESC (optional, default to .asc)
     - parameter searchFilter: (query) Optional search filter (optional)
     - parameter since: (query) Filter by created at after the given timestamp (optional)
     - parameter before: (query) Filter by created at before the given timestamp (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: Promise<PageWebhookProjection>
     */
    open class func getInboxWebhooksPaginated( inboxId: UUID,  page: Int? = nil,  size: Int? = nil,  sort: Sort_getInboxWebhooksPaginated? = nil,  searchFilter: String? = nil,  since: Date? = nil,  before: Date? = nil, apiResponseQueue: DispatchQueue = mailslurpAPI.apiResponseQueue) -> Promise<PageWebhookProjection> {
        let deferred = Promise<PageWebhookProjection>.pending()
        getInboxWebhooksPaginatedWithRequestBuilder(inboxId: inboxId, page: page, size: size, sort: sort, searchFilter: searchFilter, since: since, before: before).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                deferred.resolver.fulfill(response.body!)
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     Get paginated webhooks for an Inbox
     - GET /inboxes/{inboxId}/webhooks/paginated
     - API Key:
       - type: apiKey x-api-key 
       - name: API_KEY
     - parameter inboxId: (path)  
     - parameter page: (query) Optional page index in list pagination (optional, default to 0)
     - parameter size: (query) Optional page size in list pagination (optional, default to 20)
     - parameter sort: (query) Optional createdAt sort direction ASC or DESC (optional, default to .asc)
     - parameter searchFilter: (query) Optional search filter (optional)
     - parameter since: (query) Filter by created at after the given timestamp (optional)
     - parameter before: (query) Filter by created at before the given timestamp (optional)
     - returns: RequestBuilder<PageWebhookProjection> 
     */
    open class func getInboxWebhooksPaginatedWithRequestBuilder(inboxId: UUID, page: Int? = nil, size: Int? = nil, sort: Sort_getInboxWebhooksPaginated? = nil, searchFilter: String? = nil, since: Date? = nil, before: Date? = nil) -> RequestBuilder<PageWebhookProjection> {
        var path = "/inboxes/{inboxId}/webhooks/paginated"
        let inboxIdPreEscape = "\(APIHelper.mapValueToPathItem(inboxId))"
        let inboxIdPostEscape = inboxIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{inboxId}", with: inboxIdPostEscape, options: .literal, range: nil)
        let URLString = mailslurpAPI.basePath + path
        let parameters: [String: Any]? = nil

        var urlComponents = URLComponents(string: URLString)
        urlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "page": page?.encodeToJSON(),
            "size": size?.encodeToJSON(),
            "sort": sort?.encodeToJSON(),
            "searchFilter": searchFilter?.encodeToJSON(),
            "since": since?.encodeToJSON(),
            "before": before?.encodeToJSON(),
        ])

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<PageWebhookProjection>.Type = mailslurpAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**
     * enum for parameter event
     */
    public enum Event_getJsonSchemaForWebhookEvent: String, CaseIterable {
        case emailReceived = "EMAIL_RECEIVED"
        case newEmail = "NEW_EMAIL"
        case newContact = "NEW_CONTACT"
        case newAttachment = "NEW_ATTACHMENT"
        case emailOpened = "EMAIL_OPENED"
        case emailRead = "EMAIL_READ"
        case bounce = "BOUNCE"
        case bounceRecipient = "BOUNCE_RECIPIENT"
    }

    /**

     - parameter event: (query)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: Promise<JSONSchemaDto>
     */
    open class func getJsonSchemaForWebhookEvent( event: Event_getJsonSchemaForWebhookEvent, apiResponseQueue: DispatchQueue = mailslurpAPI.apiResponseQueue) -> Promise<JSONSchemaDto> {
        let deferred = Promise<JSONSchemaDto>.pending()
        getJsonSchemaForWebhookEventWithRequestBuilder(event: event).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                deferred.resolver.fulfill(response.body!)
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     - POST /webhooks/schema
     - Get JSON Schema definition for webhook payload by event
     - API Key:
       - type: apiKey x-api-key 
       - name: API_KEY
     - parameter event: (query)  
     - returns: RequestBuilder<JSONSchemaDto> 
     */
    open class func getJsonSchemaForWebhookEventWithRequestBuilder(event: Event_getJsonSchemaForWebhookEvent) -> RequestBuilder<JSONSchemaDto> {
        let path = "/webhooks/schema"
        let URLString = mailslurpAPI.basePath + path
        let parameters: [String: Any]? = nil

        var urlComponents = URLComponents(string: URLString)
        urlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "event": event.encodeToJSON(),
        ])

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<JSONSchemaDto>.Type = mailslurpAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**

     - parameter webhookId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: Promise<JSONSchemaDto>
     */
    open class func getJsonSchemaForWebhookPayload( webhookId: UUID, apiResponseQueue: DispatchQueue = mailslurpAPI.apiResponseQueue) -> Promise<JSONSchemaDto> {
        let deferred = Promise<JSONSchemaDto>.pending()
        getJsonSchemaForWebhookPayloadWithRequestBuilder(webhookId: webhookId).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                deferred.resolver.fulfill(response.body!)
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     - POST /webhooks/{webhookId}/schema
     - Get JSON Schema definition for webhook payload
     - API Key:
       - type: apiKey x-api-key 
       - name: API_KEY
     - parameter webhookId: (path)  
     - returns: RequestBuilder<JSONSchemaDto> 
     */
    open class func getJsonSchemaForWebhookPayloadWithRequestBuilder(webhookId: UUID) -> RequestBuilder<JSONSchemaDto> {
        var path = "/webhooks/{webhookId}/schema"
        let webhookIdPreEscape = "\(APIHelper.mapValueToPathItem(webhookId))"
        let webhookIdPostEscape = webhookIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{webhookId}", with: webhookIdPostEscape, options: .literal, range: nil)
        let URLString = mailslurpAPI.basePath + path
        let parameters: [String: Any]? = nil

        let urlComponents = URLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<JSONSchemaDto>.Type = mailslurpAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**
     * enum for parameter eventName
     */
    public enum EventName_getTestWebhookPayload: String, CaseIterable {
        case emailReceived = "EMAIL_RECEIVED"
        case newEmail = "NEW_EMAIL"
        case newContact = "NEW_CONTACT"
        case newAttachment = "NEW_ATTACHMENT"
        case emailOpened = "EMAIL_OPENED"
        case emailRead = "EMAIL_READ"
        case bounce = "BOUNCE"
        case bounceRecipient = "BOUNCE_RECIPIENT"
    }

    /**

     - parameter eventName: (query)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: Promise<AbstractWebhookPayload>
     */
    open class func getTestWebhookPayload( eventName: EventName_getTestWebhookPayload? = nil, apiResponseQueue: DispatchQueue = mailslurpAPI.apiResponseQueue) -> Promise<AbstractWebhookPayload> {
        let deferred = Promise<AbstractWebhookPayload>.pending()
        getTestWebhookPayloadWithRequestBuilder(eventName: eventName).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                deferred.resolver.fulfill(response.body!)
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     - GET /webhooks/test
     - Get test webhook payload example. Response content depends on eventName passed. Uses `EMAIL_RECEIVED` as default.
     - API Key:
       - type: apiKey x-api-key 
       - name: API_KEY
     - parameter eventName: (query)  (optional)
     - returns: RequestBuilder<AbstractWebhookPayload> 
     */
    open class func getTestWebhookPayloadWithRequestBuilder(eventName: EventName_getTestWebhookPayload? = nil) -> RequestBuilder<AbstractWebhookPayload> {
        let path = "/webhooks/test"
        let URLString = mailslurpAPI.basePath + path
        let parameters: [String: Any]? = nil

        var urlComponents = URLComponents(string: URLString)
        urlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "eventName": eventName?.encodeToJSON(),
        ])

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<AbstractWebhookPayload>.Type = mailslurpAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**

     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: Promise<WebhookBouncePayload>
     */
    open class func getTestWebhookPayloadBounce(apiResponseQueue: DispatchQueue = mailslurpAPI.apiResponseQueue) -> Promise<WebhookBouncePayload> {
        let deferred = Promise<WebhookBouncePayload>.pending()
        getTestWebhookPayloadBounceWithRequestBuilder().execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                deferred.resolver.fulfill(response.body!)
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     - GET /webhooks/test/email-bounce-payload
     - Get webhook test payload for bounce
     - API Key:
       - type: apiKey x-api-key 
       - name: API_KEY
     - returns: RequestBuilder<WebhookBouncePayload> 
     */
    open class func getTestWebhookPayloadBounceWithRequestBuilder() -> RequestBuilder<WebhookBouncePayload> {
        let path = "/webhooks/test/email-bounce-payload"
        let URLString = mailslurpAPI.basePath + path
        let parameters: [String: Any]? = nil

        let urlComponents = URLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<WebhookBouncePayload>.Type = mailslurpAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**

     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: Promise<WebhookBounceRecipientPayload>
     */
    open class func getTestWebhookPayloadBounceRecipient(apiResponseQueue: DispatchQueue = mailslurpAPI.apiResponseQueue) -> Promise<WebhookBounceRecipientPayload> {
        let deferred = Promise<WebhookBounceRecipientPayload>.pending()
        getTestWebhookPayloadBounceRecipientWithRequestBuilder().execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                deferred.resolver.fulfill(response.body!)
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     - GET /webhooks/test/email-bounce-recipient-payload
     - Get webhook test payload for bounce recipient
     - API Key:
       - type: apiKey x-api-key 
       - name: API_KEY
     - returns: RequestBuilder<WebhookBounceRecipientPayload> 
     */
    open class func getTestWebhookPayloadBounceRecipientWithRequestBuilder() -> RequestBuilder<WebhookBounceRecipientPayload> {
        let path = "/webhooks/test/email-bounce-recipient-payload"
        let URLString = mailslurpAPI.basePath + path
        let parameters: [String: Any]? = nil

        let urlComponents = URLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<WebhookBounceRecipientPayload>.Type = mailslurpAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**

     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: Promise<WebhookEmailOpenedPayload>
     */
    open class func getTestWebhookPayloadEmailOpened(apiResponseQueue: DispatchQueue = mailslurpAPI.apiResponseQueue) -> Promise<WebhookEmailOpenedPayload> {
        let deferred = Promise<WebhookEmailOpenedPayload>.pending()
        getTestWebhookPayloadEmailOpenedWithRequestBuilder().execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                deferred.resolver.fulfill(response.body!)
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     - GET /webhooks/test/email-opened-payload
     - Get webhook test payload for email opened event
     - API Key:
       - type: apiKey x-api-key 
       - name: API_KEY
     - returns: RequestBuilder<WebhookEmailOpenedPayload> 
     */
    open class func getTestWebhookPayloadEmailOpenedWithRequestBuilder() -> RequestBuilder<WebhookEmailOpenedPayload> {
        let path = "/webhooks/test/email-opened-payload"
        let URLString = mailslurpAPI.basePath + path
        let parameters: [String: Any]? = nil

        let urlComponents = URLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<WebhookEmailOpenedPayload>.Type = mailslurpAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**

     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: Promise<WebhookEmailReadPayload>
     */
    open class func getTestWebhookPayloadEmailRead(apiResponseQueue: DispatchQueue = mailslurpAPI.apiResponseQueue) -> Promise<WebhookEmailReadPayload> {
        let deferred = Promise<WebhookEmailReadPayload>.pending()
        getTestWebhookPayloadEmailReadWithRequestBuilder().execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                deferred.resolver.fulfill(response.body!)
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     - GET /webhooks/test/email-read-payload
     - Get webhook test payload for email opened event
     - API Key:
       - type: apiKey x-api-key 
       - name: API_KEY
     - returns: RequestBuilder<WebhookEmailReadPayload> 
     */
    open class func getTestWebhookPayloadEmailReadWithRequestBuilder() -> RequestBuilder<WebhookEmailReadPayload> {
        let path = "/webhooks/test/email-read-payload"
        let URLString = mailslurpAPI.basePath + path
        let parameters: [String: Any]? = nil

        let urlComponents = URLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<WebhookEmailReadPayload>.Type = mailslurpAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**

     - parameter webhookId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: Promise<AbstractWebhookPayload>
     */
    open class func getTestWebhookPayloadForWebhook( webhookId: UUID, apiResponseQueue: DispatchQueue = mailslurpAPI.apiResponseQueue) -> Promise<AbstractWebhookPayload> {
        let deferred = Promise<AbstractWebhookPayload>.pending()
        getTestWebhookPayloadForWebhookWithRequestBuilder(webhookId: webhookId).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                deferred.resolver.fulfill(response.body!)
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     - POST /webhooks/{webhookId}/example
     - Get example payload for webhook
     - API Key:
       - type: apiKey x-api-key 
       - name: API_KEY
     - parameter webhookId: (path)  
     - returns: RequestBuilder<AbstractWebhookPayload> 
     */
    open class func getTestWebhookPayloadForWebhookWithRequestBuilder(webhookId: UUID) -> RequestBuilder<AbstractWebhookPayload> {
        var path = "/webhooks/{webhookId}/example"
        let webhookIdPreEscape = "\(APIHelper.mapValueToPathItem(webhookId))"
        let webhookIdPostEscape = webhookIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{webhookId}", with: webhookIdPostEscape, options: .literal, range: nil)
        let URLString = mailslurpAPI.basePath + path
        let parameters: [String: Any]? = nil

        let urlComponents = URLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<AbstractWebhookPayload>.Type = mailslurpAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**
     Get webhook test payload for new attachment event
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: Promise<WebhookNewAttachmentPayload>
     */
    open class func getTestWebhookPayloadNewAttachment(apiResponseQueue: DispatchQueue = mailslurpAPI.apiResponseQueue) -> Promise<WebhookNewAttachmentPayload> {
        let deferred = Promise<WebhookNewAttachmentPayload>.pending()
        getTestWebhookPayloadNewAttachmentWithRequestBuilder().execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                deferred.resolver.fulfill(response.body!)
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     Get webhook test payload for new attachment event
     - GET /webhooks/test/new-attachment-payload
     - API Key:
       - type: apiKey x-api-key 
       - name: API_KEY
     - returns: RequestBuilder<WebhookNewAttachmentPayload> 
     */
    open class func getTestWebhookPayloadNewAttachmentWithRequestBuilder() -> RequestBuilder<WebhookNewAttachmentPayload> {
        let path = "/webhooks/test/new-attachment-payload"
        let URLString = mailslurpAPI.basePath + path
        let parameters: [String: Any]? = nil

        let urlComponents = URLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<WebhookNewAttachmentPayload>.Type = mailslurpAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**
     Get webhook test payload for new contact event
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: Promise<WebhookNewContactPayload>
     */
    open class func getTestWebhookPayloadNewContact(apiResponseQueue: DispatchQueue = mailslurpAPI.apiResponseQueue) -> Promise<WebhookNewContactPayload> {
        let deferred = Promise<WebhookNewContactPayload>.pending()
        getTestWebhookPayloadNewContactWithRequestBuilder().execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                deferred.resolver.fulfill(response.body!)
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     Get webhook test payload for new contact event
     - GET /webhooks/test/new-contact-payload
     - API Key:
       - type: apiKey x-api-key 
       - name: API_KEY
     - returns: RequestBuilder<WebhookNewContactPayload> 
     */
    open class func getTestWebhookPayloadNewContactWithRequestBuilder() -> RequestBuilder<WebhookNewContactPayload> {
        let path = "/webhooks/test/new-contact-payload"
        let URLString = mailslurpAPI.basePath + path
        let parameters: [String: Any]? = nil

        let urlComponents = URLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<WebhookNewContactPayload>.Type = mailslurpAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**
     Get webhook test payload for new email event
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: Promise<WebhookNewEmailPayload>
     */
    open class func getTestWebhookPayloadNewEmail(apiResponseQueue: DispatchQueue = mailslurpAPI.apiResponseQueue) -> Promise<WebhookNewEmailPayload> {
        let deferred = Promise<WebhookNewEmailPayload>.pending()
        getTestWebhookPayloadNewEmailWithRequestBuilder().execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                deferred.resolver.fulfill(response.body!)
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     Get webhook test payload for new email event
     - GET /webhooks/test/new-email-payload
     - API Key:
       - type: apiKey x-api-key 
       - name: API_KEY
     - returns: RequestBuilder<WebhookNewEmailPayload> 
     */
    open class func getTestWebhookPayloadNewEmailWithRequestBuilder() -> RequestBuilder<WebhookNewEmailPayload> {
        let path = "/webhooks/test/new-email-payload"
        let URLString = mailslurpAPI.basePath + path
        let parameters: [String: Any]? = nil

        let urlComponents = URLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<WebhookNewEmailPayload>.Type = mailslurpAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**
     Get a webhook
     
     - parameter webhookId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: Promise<WebhookDto>
     */
    open class func getWebhook( webhookId: UUID, apiResponseQueue: DispatchQueue = mailslurpAPI.apiResponseQueue) -> Promise<WebhookDto> {
        let deferred = Promise<WebhookDto>.pending()
        getWebhookWithRequestBuilder(webhookId: webhookId).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                deferred.resolver.fulfill(response.body!)
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     Get a webhook
     - GET /webhooks/{webhookId}
     - API Key:
       - type: apiKey x-api-key 
       - name: API_KEY
     - parameter webhookId: (path)  
     - returns: RequestBuilder<WebhookDto> 
     */
    open class func getWebhookWithRequestBuilder(webhookId: UUID) -> RequestBuilder<WebhookDto> {
        var path = "/webhooks/{webhookId}"
        let webhookIdPreEscape = "\(APIHelper.mapValueToPathItem(webhookId))"
        let webhookIdPostEscape = webhookIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{webhookId}", with: webhookIdPostEscape, options: .literal, range: nil)
        let URLString = mailslurpAPI.basePath + path
        let parameters: [String: Any]? = nil

        let urlComponents = URLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<WebhookDto>.Type = mailslurpAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**
     Get a webhook result for a webhook
     
     - parameter webhookResultId: (path) Webhook Result ID 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: Promise<WebhookResultDto>
     */
    open class func getWebhookResult( webhookResultId: UUID, apiResponseQueue: DispatchQueue = mailslurpAPI.apiResponseQueue) -> Promise<WebhookResultDto> {
        let deferred = Promise<WebhookResultDto>.pending()
        getWebhookResultWithRequestBuilder(webhookResultId: webhookResultId).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                deferred.resolver.fulfill(response.body!)
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     Get a webhook result for a webhook
     - GET /webhooks/results/{webhookResultId}
     - API Key:
       - type: apiKey x-api-key 
       - name: API_KEY
     - parameter webhookResultId: (path) Webhook Result ID 
     - returns: RequestBuilder<WebhookResultDto> 
     */
    open class func getWebhookResultWithRequestBuilder(webhookResultId: UUID) -> RequestBuilder<WebhookResultDto> {
        var path = "/webhooks/results/{webhookResultId}"
        let webhookResultIdPreEscape = "\(APIHelper.mapValueToPathItem(webhookResultId))"
        let webhookResultIdPostEscape = webhookResultIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{webhookResultId}", with: webhookResultIdPostEscape, options: .literal, range: nil)
        let URLString = mailslurpAPI.basePath + path
        let parameters: [String: Any]? = nil

        let urlComponents = URLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<WebhookResultDto>.Type = mailslurpAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**
     * enum for parameter sort
     */
    public enum Sort_getWebhookResults: String, CaseIterable {
        case asc = "ASC"
        case desc = "DESC"
    }

    /**
     Get a webhook results for a webhook
     
     - parameter webhookId: (path) ID of webhook to get results for 
     - parameter page: (query) Optional page index in list pagination (optional, default to 0)
     - parameter size: (query) Optional page size in list pagination (optional, default to 20)
     - parameter sort: (query) Optional createdAt sort direction ASC or DESC (optional, default to .asc)
     - parameter searchFilter: (query) Optional search filter (optional)
     - parameter since: (query) Filter by created at after the given timestamp (optional)
     - parameter before: (query) Filter by created at before the given timestamp (optional)
     - parameter unseenOnly: (query) Filter for unseen exceptions only (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: Promise<PageWebhookResult>
     */
    open class func getWebhookResults( webhookId: UUID,  page: Int? = nil,  size: Int? = nil,  sort: Sort_getWebhookResults? = nil,  searchFilter: String? = nil,  since: Date? = nil,  before: Date? = nil,  unseenOnly: Bool? = nil, apiResponseQueue: DispatchQueue = mailslurpAPI.apiResponseQueue) -> Promise<PageWebhookResult> {
        let deferred = Promise<PageWebhookResult>.pending()
        getWebhookResultsWithRequestBuilder(webhookId: webhookId, page: page, size: size, sort: sort, searchFilter: searchFilter, since: since, before: before, unseenOnly: unseenOnly).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                deferred.resolver.fulfill(response.body!)
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     Get a webhook results for a webhook
     - GET /webhooks/{webhookId}/results
     - API Key:
       - type: apiKey x-api-key 
       - name: API_KEY
     - parameter webhookId: (path) ID of webhook to get results for 
     - parameter page: (query) Optional page index in list pagination (optional, default to 0)
     - parameter size: (query) Optional page size in list pagination (optional, default to 20)
     - parameter sort: (query) Optional createdAt sort direction ASC or DESC (optional, default to .asc)
     - parameter searchFilter: (query) Optional search filter (optional)
     - parameter since: (query) Filter by created at after the given timestamp (optional)
     - parameter before: (query) Filter by created at before the given timestamp (optional)
     - parameter unseenOnly: (query) Filter for unseen exceptions only (optional)
     - returns: RequestBuilder<PageWebhookResult> 
     */
    open class func getWebhookResultsWithRequestBuilder(webhookId: UUID, page: Int? = nil, size: Int? = nil, sort: Sort_getWebhookResults? = nil, searchFilter: String? = nil, since: Date? = nil, before: Date? = nil, unseenOnly: Bool? = nil) -> RequestBuilder<PageWebhookResult> {
        var path = "/webhooks/{webhookId}/results"
        let webhookIdPreEscape = "\(APIHelper.mapValueToPathItem(webhookId))"
        let webhookIdPostEscape = webhookIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{webhookId}", with: webhookIdPostEscape, options: .literal, range: nil)
        let URLString = mailslurpAPI.basePath + path
        let parameters: [String: Any]? = nil

        var urlComponents = URLComponents(string: URLString)
        urlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "page": page?.encodeToJSON(),
            "size": size?.encodeToJSON(),
            "sort": sort?.encodeToJSON(),
            "searchFilter": searchFilter?.encodeToJSON(),
            "since": since?.encodeToJSON(),
            "before": before?.encodeToJSON(),
            "unseenOnly": unseenOnly?.encodeToJSON(),
        ])

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<PageWebhookResult>.Type = mailslurpAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**
     Get count of unseen webhook results with error status
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: Promise<UnseenErrorCountDto>
     */
    open class func getWebhookResultsUnseenErrorCount(apiResponseQueue: DispatchQueue = mailslurpAPI.apiResponseQueue) -> Promise<UnseenErrorCountDto> {
        let deferred = Promise<UnseenErrorCountDto>.pending()
        getWebhookResultsUnseenErrorCountWithRequestBuilder().execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                deferred.resolver.fulfill(response.body!)
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     Get count of unseen webhook results with error status
     - GET /webhooks/results/unseen-count
     - API Key:
       - type: apiKey x-api-key 
       - name: API_KEY
     - returns: RequestBuilder<UnseenErrorCountDto> 
     */
    open class func getWebhookResultsUnseenErrorCountWithRequestBuilder() -> RequestBuilder<UnseenErrorCountDto> {
        let path = "/webhooks/results/unseen-count"
        let URLString = mailslurpAPI.basePath + path
        let parameters: [String: Any]? = nil

        let urlComponents = URLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<UnseenErrorCountDto>.Type = mailslurpAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**
     Get all webhooks for an Inbox
     
     - parameter inboxId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: Promise<[WebhookDto]>
     */
    open class func getWebhooks( inboxId: UUID, apiResponseQueue: DispatchQueue = mailslurpAPI.apiResponseQueue) -> Promise<[WebhookDto]> {
        let deferred = Promise<[WebhookDto]>.pending()
        getWebhooksWithRequestBuilder(inboxId: inboxId).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                deferred.resolver.fulfill(response.body!)
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     Get all webhooks for an Inbox
     - GET /inboxes/{inboxId}/webhooks
     - API Key:
       - type: apiKey x-api-key 
       - name: API_KEY
     - parameter inboxId: (path)  
     - returns: RequestBuilder<[WebhookDto]> 
     */
    open class func getWebhooksWithRequestBuilder(inboxId: UUID) -> RequestBuilder<[WebhookDto]> {
        var path = "/inboxes/{inboxId}/webhooks"
        let inboxIdPreEscape = "\(APIHelper.mapValueToPathItem(inboxId))"
        let inboxIdPostEscape = inboxIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{inboxId}", with: inboxIdPostEscape, options: .literal, range: nil)
        let URLString = mailslurpAPI.basePath + path
        let parameters: [String: Any]? = nil

        let urlComponents = URLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<[WebhookDto]>.Type = mailslurpAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**
     Get a webhook result and try to resend the original webhook payload
     
     - parameter webhookResultId: (path) Webhook Result ID 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: Promise<WebhookRedriveResult>
     */
    open class func redriveWebhookResult( webhookResultId: UUID, apiResponseQueue: DispatchQueue = mailslurpAPI.apiResponseQueue) -> Promise<WebhookRedriveResult> {
        let deferred = Promise<WebhookRedriveResult>.pending()
        redriveWebhookResultWithRequestBuilder(webhookResultId: webhookResultId).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                deferred.resolver.fulfill(response.body!)
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     Get a webhook result and try to resend the original webhook payload
     - POST /webhooks/results/{webhookResultId}/redrive
     - Allows you to resend a webhook payload that was already sent. Webhooks that fail are retried automatically for 24 hours and then put in a dead letter queue. You can retry results manually using this method.
     - API Key:
       - type: apiKey x-api-key 
       - name: API_KEY
     - parameter webhookResultId: (path) Webhook Result ID 
     - returns: RequestBuilder<WebhookRedriveResult> 
     */
    open class func redriveWebhookResultWithRequestBuilder(webhookResultId: UUID) -> RequestBuilder<WebhookRedriveResult> {
        var path = "/webhooks/results/{webhookResultId}/redrive"
        let webhookResultIdPreEscape = "\(APIHelper.mapValueToPathItem(webhookResultId))"
        let webhookResultIdPostEscape = webhookResultIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{webhookResultId}", with: webhookResultIdPostEscape, options: .literal, range: nil)
        let URLString = mailslurpAPI.basePath + path
        let parameters: [String: Any]? = nil

        let urlComponents = URLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<WebhookRedriveResult>.Type = mailslurpAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**
     Send webhook test data
     
     - parameter webhookId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: Promise<WebhookTestResult>
     */
    open class func sendTestData( webhookId: UUID, apiResponseQueue: DispatchQueue = mailslurpAPI.apiResponseQueue) -> Promise<WebhookTestResult> {
        let deferred = Promise<WebhookTestResult>.pending()
        sendTestDataWithRequestBuilder(webhookId: webhookId).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                deferred.resolver.fulfill(response.body!)
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     Send webhook test data
     - POST /webhooks/{webhookId}/test
     - API Key:
       - type: apiKey x-api-key 
       - name: API_KEY
     - parameter webhookId: (path)  
     - returns: RequestBuilder<WebhookTestResult> 
     */
    open class func sendTestDataWithRequestBuilder(webhookId: UUID) -> RequestBuilder<WebhookTestResult> {
        var path = "/webhooks/{webhookId}/test"
        let webhookIdPreEscape = "\(APIHelper.mapValueToPathItem(webhookId))"
        let webhookIdPostEscape = webhookIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{webhookId}", with: webhookIdPostEscape, options: .literal, range: nil)
        let URLString = mailslurpAPI.basePath + path
        let parameters: [String: Any]? = nil

        let urlComponents = URLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<WebhookTestResult>.Type = mailslurpAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**
     Verify a webhook payload signature
     
     - parameter verifyWebhookSignatureOptions: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: Promise<VerifyWebhookSignatureResults>
     */
    open class func verifyWebhookSignature( verifyWebhookSignatureOptions: VerifyWebhookSignatureOptions, apiResponseQueue: DispatchQueue = mailslurpAPI.apiResponseQueue) -> Promise<VerifyWebhookSignatureResults> {
        let deferred = Promise<VerifyWebhookSignatureResults>.pending()
        verifyWebhookSignatureWithRequestBuilder(verifyWebhookSignatureOptions: verifyWebhookSignatureOptions).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                deferred.resolver.fulfill(response.body!)
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     Verify a webhook payload signature
     - POST /webhooks/verify
     - Verify a webhook payload using the messageId and signature. This allows you to be sure that MailSlurp sent the payload and not another server.
     - API Key:
       - type: apiKey x-api-key 
       - name: API_KEY
     - parameter verifyWebhookSignatureOptions: (body)  
     - returns: RequestBuilder<VerifyWebhookSignatureResults> 
     */
    open class func verifyWebhookSignatureWithRequestBuilder(verifyWebhookSignatureOptions: VerifyWebhookSignatureOptions) -> RequestBuilder<VerifyWebhookSignatureResults> {
        let path = "/webhooks/verify"
        let URLString = mailslurpAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: verifyWebhookSignatureOptions)

        let urlComponents = URLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<VerifyWebhookSignatureResults>.Type = mailslurpAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

}
