//
// AbstractWebhookPayload.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



@objc public class AbstractWebhookPayload: NSObject, Codable { 

    public enum EventName: String, Codable, CaseIterable {
        case emailReceived = "EMAIL_RECEIVED"
        case newEmail = "NEW_EMAIL"
        case newContact = "NEW_CONTACT"
        case newAttachment = "NEW_ATTACHMENT"
    }
    public var eventName: EventName
    public var messageId: String
    public var webhookId: UUID
    public var webhookName: String?

    public init(eventName: EventName, messageId: String, webhookId: UUID, webhookName: String?) {
        self.eventName = eventName
        self.messageId = messageId
        self.webhookId = webhookId
        self.webhookName = webhookName
    }

}
