//
// AliasProjection.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable
import AnyCodable

/** Representation of a alias */
@objc public class AliasProjection: NSObject, Codable {

    public var name: String?
    public var _id: UUID
    public var userId: UUID
    public var emailAddress: String
    public var inboxId: UUID
    public var createdAt: Date
    public var useThreads: Bool?
    public var useThreadsNum: NSNumber? {
        get {
            return useThreads as NSNumber?
        }
    }
    public var updatedAt: Date

    public init(name: String? = nil, _id: UUID, userId: UUID, emailAddress: String, inboxId: UUID, createdAt: Date, useThreads: Bool? = nil, updatedAt: Date) {
        self.name = name
        self._id = _id
        self.userId = userId
        self.emailAddress = emailAddress
        self.inboxId = inboxId
        self.createdAt = createdAt
        self.useThreads = useThreads
        self.updatedAt = updatedAt
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case _id = "id"
        case userId
        case emailAddress
        case inboxId
        case createdAt
        case useThreads
        case updatedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encode(_id, forKey: ._id)
        try container.encode(userId, forKey: .userId)
        try container.encode(emailAddress, forKey: .emailAddress)
        try container.encode(inboxId, forKey: .inboxId)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(useThreads, forKey: .useThreads)
        try container.encode(updatedAt, forKey: .updatedAt)
    }



}
