//
// BulkSendEmailOptions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Options for bulk sending an email from multiple addresses. See regular &#x60;sendEmail&#x60; methods for more information. */
@objc public class BulkSendEmailOptions: NSObject, Codable {

    /** Inboxes to send the email from */
    public var inboxIds: [UUID]?
    public var sendEmailOptions: SendEmailOptions?

    public init(inboxIds: [UUID]? = nil, sendEmailOptions: SendEmailOptions? = nil) {
        self.inboxIds = inboxIds
        self.sendEmailOptions = sendEmailOptions
    }

}
