//
// BulkSendEmailOptions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable
import AnyCodable

/** Options for bulk sending an email from multiple addresses. See regular &#x60;sendEmail&#x60; methods for more information. */
@objc public class BulkSendEmailOptions: NSObject, Codable {

    /** Inboxes to send the email from */
    public var inboxIds: [UUID]?
    public var sendEmailOptions: SendEmailOptions?

    public init(inboxIds: [UUID]? = nil, sendEmailOptions: SendEmailOptions? = nil) {
        self.inboxIds = inboxIds
        self.sendEmailOptions = sendEmailOptions
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case inboxIds
        case sendEmailOptions
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(inboxIds, forKey: .inboxIds)
        try container.encodeIfPresent(sendEmailOptions, forKey: .sendEmailOptions)
    }



}
