//
// CreateInboxForwarderOptions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable
import AnyCodable

@objc public class CreateInboxForwarderOptions: NSObject, Codable {

    public enum Field: String, Codable, CaseIterable {
        case recipients = "RECIPIENTS"
        case sender = "SENDER"
        case subject = "SUBJECT"
        case attachments = "ATTACHMENTS"
    }
    public var field: Field
    public var match: String
    public var forwardToRecipients: [String]

    public init(field: Field, match: String, forwardToRecipients: [String]) {
        self.field = field
        self.match = match
        self.forwardToRecipients = forwardToRecipients
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case field
        case match
        case forwardToRecipients
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(field, forKey: .field)
        try container.encode(match, forKey: .match)
        try container.encode(forwardToRecipients, forKey: .forwardToRecipients)
    }



}
