//
// DescribeDomainOptions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



@objc public class DescribeDomainOptions: NSObject, Codable { 

    public var domain: String

    public init(domain: String) {
        self.domain = domain
    }

}
