//
// DescribeMailServerDomainResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Name Server lookup result */

@objc public class DescribeMailServerDomainResult: NSObject, Codable { 

    public var domain: String
    public var message: String?
    public var mxRecords: [NameServerRecord]

    public init(domain: String, message: String?, mxRecords: [NameServerRecord]) {
        self.domain = domain
        self.message = message
        self.mxRecords = mxRecords
    }

}
