//
// ExpirationDefaults.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Expiration defaults for your account */
@objc public class ExpirationDefaults: NSObject, Codable {

    public var canPermanentInbox: Bool
    public var defaultExpirationMillis: Int64?
    public var defaultExpirationMillisNum: NSNumber? {
        get {
            return defaultExpirationMillis as NSNumber?
        }
    }
    public var defaultExpiresAt: Date?
    public var maxExpirationMillis: Int64?
    public var maxExpirationMillisNum: NSNumber? {
        get {
            return maxExpirationMillis as NSNumber?
        }
    }

    public init(canPermanentInbox: Bool, defaultExpirationMillis: Int64? = nil, defaultExpiresAt: Date? = nil, maxExpirationMillis: Int64? = nil) {
        self.canPermanentInbox = canPermanentInbox
        self.defaultExpirationMillis = defaultExpirationMillis
        self.defaultExpiresAt = defaultExpiresAt
        self.maxExpirationMillis = maxExpirationMillis
    }

}
