//
// ExportOptions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Options for exporting user data */
@objc public class ExportOptions: NSObject, Codable {

    public enum OutputFormat: String, Codable, CaseIterable {
        case _default = "CSV_DEFAULT"
        case excel = "CSV_EXCEL"
    }
    public var outputFormat: OutputFormat
    public var excludePreviouslyExported: Bool?
    public var excludePreviouslyExportedNum: NSNumber? {
        get {
            return excludePreviouslyExported as NSNumber?
        }
    }
    public var createdEarliestTime: Date?
    public var createdOldestTime: Date?
    public var filter: String?
    public var listSeparatorToken: Any?

    public init(outputFormat: OutputFormat, excludePreviouslyExported: Bool? = nil, createdEarliestTime: Date? = nil, createdOldestTime: Date? = nil, filter: String? = nil, listSeparatorToken: Any? = nil) {
        self.outputFormat = outputFormat
        self.excludePreviouslyExported = excludePreviouslyExported
        self.createdEarliestTime = createdEarliestTime
        self.createdOldestTime = createdOldestTime
        self.filter = filter
        self.listSeparatorToken = listSeparatorToken
    }

}
