//
// GroupDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable
import AnyCodable

@objc public class GroupDto: NSObject, Codable {

    public var createdAt: Date
    public var _description: String?
    public var _id: UUID
    public var name: String

    public init(createdAt: Date, _description: String? = nil, _id: UUID, name: String) {
        self.createdAt = createdAt
        self._description = _description
        self._id = _id
        self.name = name
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case createdAt
        case _description = "description"
        case _id = "id"
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(_description, forKey: ._description)
        try container.encode(_id, forKey: ._id)
        try container.encode(name, forKey: .name)
    }



}
