//
// HTMLValidationResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** HTML Validation Results */
@objc public class HTMLValidationResult: NSObject, Codable {

    /** Optional errors resulting from HTML validation */
    public var errors: [ValidationMessage]?
    /** Is HTML validation result valid */
    public var isValid: Bool?
    public var isValidNum: NSNumber? {
        get {
            return isValid as NSNumber?
        }
    }
    /** Optional warnings resulting from HTML validation */
    public var warnings: [ValidationMessage]?

    public init(errors: [ValidationMessage]? = nil, isValid: Bool? = nil, warnings: [ValidationMessage]? = nil) {
        self.errors = errors
        self.isValid = isValid
        self.warnings = warnings
    }

}
