//
// MatchOptions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Optional filter for matching emails based on fields. For instance filter results to only include emails whose &#x60;SUBJECT&#x60; value does &#x60;CONTAIN&#x60; given match value. An example payload would be &#x60;{ matches: [{ field: &#39;SUBJECT&#39;, should: &#39;CONTAIN&#39;, value: &#39;Welcome&#39; }] }&#x60;. If you wish to extract regex matches inside the email content see the &#x60;getEmailContentMatch&#x60; method in the EmailController. */

@objc public class MatchOptions: NSObject, Codable { 

    /** 1 or more match options. Options are additive so if one does not match the email is excluded from results */
    public var matches: [MatchOption]?

    public init(matches: [MatchOption]?) {
        self.matches = matches
    }

}
