//
// MissedEmailProjection.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable
import AnyCodable

@objc public class MissedEmailProjection: NSObject, Codable {

    public var _id: UUID?
    public var from: String?
    public var subject: String?
    public var userId: UUID?
    public var createdAt: Date?

    public init(_id: UUID? = nil, from: String? = nil, subject: String? = nil, userId: UUID? = nil, createdAt: Date? = nil) {
        self._id = _id
        self.from = from
        self.subject = subject
        self.userId = userId
        self.createdAt = createdAt
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case _id = "id"
        case from
        case subject
        case userId
        case createdAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(_id, forKey: ._id)
        try container.encodeIfPresent(from, forKey: .from)
        try container.encodeIfPresent(subject, forKey: .subject)
        try container.encodeIfPresent(userId, forKey: .userId)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
    }



}
