//
// SetInboxFavouritedOptions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Options for setting inbox favourite state */

@objc public class SetInboxFavouritedOptions: NSObject, Codable { 

    /** Is the inbox a favorite. Marking an inbox as a favorite is typically done in the dashboard for quick access or filtering */
    public var state: Bool?
    public var stateNum: NSNumber? {
        get {
            return state as NSNumber?
        }
    }

    public init(state: Bool?) {
        self.state = state
    }

}
