//
// UpdateAliasOptions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Update an email alias */
@objc public class UpdateAliasOptions: NSObject, Codable {

    /** Optional name for alias */
    public var name: String?

    public init(name: String? = nil) {
        self.name = name
    }

}
