//
// ImapControllerAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
@preconcurrency import PromiseKit

@objcMembers open class ImapControllerAPI : NSObject {

    /**
     Fetch message in an inbox
     
     - parameter seqNum: (query)  
     - parameter inboxId: (query) Inbox ID to search (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Promise<ImapServerFetchResult>
     */
    open class func imapServerFetch(seqNum: Int64, inboxId: UUID? = nil, apiConfiguration: mailslurpAPIConfiguration = mailslurpAPIConfiguration.shared) -> Promise<ImapServerFetchResult> {
        let deferred = Promise<ImapServerFetchResult>.pending()
        imapServerFetchWithRequestBuilder(seqNum: seqNum, inboxId: inboxId, apiConfiguration: apiConfiguration).execute { result in
            switch result {
            case let .success(response):
                deferred.resolver.fulfill(response.body)
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     Fetch message in an inbox
     - POST /imap/server/fetch
     - API Key:
       - type: apiKey x-api-key (HEADER)
       - name: API_KEY
     - parameter seqNum: (query)  
     - parameter inboxId: (query) Inbox ID to search (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ImapServerFetchResult> 
     */
    open class func imapServerFetchWithRequestBuilder(seqNum: Int64, inboxId: UUID? = nil, apiConfiguration: mailslurpAPIConfiguration = mailslurpAPIConfiguration.shared) -> RequestBuilder<ImapServerFetchResult> {
        let localVariablePath = "/imap/server/fetch"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "inboxId": (wrappedValue: inboxId?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "seqNum": (wrappedValue: seqNum.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ImapServerFetchResult>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Get a message by email ID
     
     - parameter emailId: (query) Email ID to get 
     - parameter inboxId: (query) Inbox ID to search (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Promise<ImapServerGetResult>
     */
    open class func imapServerGet(emailId: UUID, inboxId: UUID? = nil, apiConfiguration: mailslurpAPIConfiguration = mailslurpAPIConfiguration.shared) -> Promise<ImapServerGetResult> {
        let deferred = Promise<ImapServerGetResult>.pending()
        imapServerGetWithRequestBuilder(emailId: emailId, inboxId: inboxId, apiConfiguration: apiConfiguration).execute { result in
            switch result {
            case let .success(response):
                deferred.resolver.fulfill(response.body)
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     Get a message by email ID
     - POST /imap/server/get
     - API Key:
       - type: apiKey x-api-key (HEADER)
       - name: API_KEY
     - parameter emailId: (query) Email ID to get 
     - parameter inboxId: (query) Inbox ID to search (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ImapServerGetResult> 
     */
    open class func imapServerGetWithRequestBuilder(emailId: UUID, inboxId: UUID? = nil, apiConfiguration: mailslurpAPIConfiguration = mailslurpAPIConfiguration.shared) -> RequestBuilder<ImapServerGetResult> {
        let localVariablePath = "/imap/server/get"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "emailId": (wrappedValue: emailId.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "inboxId": (wrappedValue: inboxId?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ImapServerGetResult>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     List messages in an inbox
     
     - parameter imapServerListOptions: (body)  
     - parameter inboxId: (query) Inbox ID to list (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Promise<ImapServerListResult>
     */
    open class func imapServerList(imapServerListOptions: ImapServerListOptions, inboxId: UUID? = nil, apiConfiguration: mailslurpAPIConfiguration = mailslurpAPIConfiguration.shared) -> Promise<ImapServerListResult> {
        let deferred = Promise<ImapServerListResult>.pending()
        imapServerListWithRequestBuilder(imapServerListOptions: imapServerListOptions, inboxId: inboxId, apiConfiguration: apiConfiguration).execute { result in
            switch result {
            case let .success(response):
                deferred.resolver.fulfill(response.body)
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     List messages in an inbox
     - POST /imap/server/list
     - API Key:
       - type: apiKey x-api-key (HEADER)
       - name: API_KEY
     - parameter imapServerListOptions: (body)  
     - parameter inboxId: (query) Inbox ID to list (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ImapServerListResult> 
     */
    open class func imapServerListWithRequestBuilder(imapServerListOptions: ImapServerListOptions, inboxId: UUID? = nil, apiConfiguration: mailslurpAPIConfiguration = mailslurpAPIConfiguration.shared) -> RequestBuilder<ImapServerListResult> {
        let localVariablePath = "/imap/server/list"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: imapServerListOptions, codableHelper: apiConfiguration.codableHelper)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "inboxId": (wrappedValue: inboxId?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ImapServerListResult>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Create a new mailbox if possible
     
     - parameter name: (query) Inbox email address to create 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Promise<ImapServerMailboxResult>
     */
    open class func imapServerMailbox(name: String, apiConfiguration: mailslurpAPIConfiguration = mailslurpAPIConfiguration.shared) -> Promise<ImapServerMailboxResult> {
        let deferred = Promise<ImapServerMailboxResult>.pending()
        imapServerMailboxWithRequestBuilder(name: name, apiConfiguration: apiConfiguration).execute { result in
            switch result {
            case let .success(response):
                deferred.resolver.fulfill(response.body)
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     Create a new mailbox if possible
     - POST /imap/server/mailbox
     - API Key:
       - type: apiKey x-api-key (HEADER)
       - name: API_KEY
     - parameter name: (query) Inbox email address to create 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ImapServerMailboxResult> 
     */
    open class func imapServerMailboxWithRequestBuilder(name: String, apiConfiguration: mailslurpAPIConfiguration = mailslurpAPIConfiguration.shared) -> RequestBuilder<ImapServerMailboxResult> {
        let localVariablePath = "/imap/server/mailbox"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "name": (wrappedValue: name.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ImapServerMailboxResult>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Search messages in an inbox
     
     - parameter imapServerSearchOptions: (body)  
     - parameter inboxId: (query) Inbox ID to search (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Promise<ImapServerSearchResult>
     */
    open class func imapServerSearch(imapServerSearchOptions: ImapServerSearchOptions, inboxId: UUID? = nil, apiConfiguration: mailslurpAPIConfiguration = mailslurpAPIConfiguration.shared) -> Promise<ImapServerSearchResult> {
        let deferred = Promise<ImapServerSearchResult>.pending()
        imapServerSearchWithRequestBuilder(imapServerSearchOptions: imapServerSearchOptions, inboxId: inboxId, apiConfiguration: apiConfiguration).execute { result in
            switch result {
            case let .success(response):
                deferred.resolver.fulfill(response.body)
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     Search messages in an inbox
     - POST /imap/server/search
     - API Key:
       - type: apiKey x-api-key (HEADER)
       - name: API_KEY
     - parameter imapServerSearchOptions: (body)  
     - parameter inboxId: (query) Inbox ID to search (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ImapServerSearchResult> 
     */
    open class func imapServerSearchWithRequestBuilder(imapServerSearchOptions: ImapServerSearchOptions, inboxId: UUID? = nil, apiConfiguration: mailslurpAPIConfiguration = mailslurpAPIConfiguration.shared) -> RequestBuilder<ImapServerSearchResult> {
        let localVariablePath = "/imap/server/search"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: imapServerSearchOptions, codableHelper: apiConfiguration.codableHelper)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "inboxId": (wrappedValue: inboxId?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ImapServerSearchResult>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Get status for mailbox
     
     - parameter imapServerStatusOptions: (body)  
     - parameter inboxId: (query) Inbox ID to list (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Promise<ImapServerStatusResult>
     */
    open class func imapServerStatus(imapServerStatusOptions: ImapServerStatusOptions, inboxId: UUID? = nil, apiConfiguration: mailslurpAPIConfiguration = mailslurpAPIConfiguration.shared) -> Promise<ImapServerStatusResult> {
        let deferred = Promise<ImapServerStatusResult>.pending()
        imapServerStatusWithRequestBuilder(imapServerStatusOptions: imapServerStatusOptions, inboxId: inboxId, apiConfiguration: apiConfiguration).execute { result in
            switch result {
            case let .success(response):
                deferred.resolver.fulfill(response.body)
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     Get status for mailbox
     - POST /imap/server/status
     - API Key:
       - type: apiKey x-api-key (HEADER)
       - name: API_KEY
     - parameter imapServerStatusOptions: (body)  
     - parameter inboxId: (query) Inbox ID to list (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ImapServerStatusResult> 
     */
    open class func imapServerStatusWithRequestBuilder(imapServerStatusOptions: ImapServerStatusOptions, inboxId: UUID? = nil, apiConfiguration: mailslurpAPIConfiguration = mailslurpAPIConfiguration.shared) -> RequestBuilder<ImapServerStatusResult> {
        let localVariablePath = "/imap/server/status"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: imapServerStatusOptions, codableHelper: apiConfiguration.codableHelper)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "inboxId": (wrappedValue: inboxId?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ImapServerStatusResult>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter imapUpdateFlagsOptions: (body)  
     - parameter inboxId: (query)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Promise<Void>
     */
    open class func imapServerUpdateFlags(imapUpdateFlagsOptions: ImapUpdateFlagsOptions, inboxId: UUID? = nil, apiConfiguration: mailslurpAPIConfiguration = mailslurpAPIConfiguration.shared) -> Promise<Void> {
        let deferred = Promise<Void>.pending()
        imapServerUpdateFlagsWithRequestBuilder(imapUpdateFlagsOptions: imapUpdateFlagsOptions, inboxId: inboxId, apiConfiguration: apiConfiguration).execute { result in
            switch result {
            case .success:
                deferred.resolver.fulfill(())
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     - POST /imap/server/update-flags
     - Update message flags
     - API Key:
       - type: apiKey x-api-key (HEADER)
       - name: API_KEY
     - parameter imapUpdateFlagsOptions: (body)  
     - parameter inboxId: (query)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func imapServerUpdateFlagsWithRequestBuilder(imapUpdateFlagsOptions: ImapUpdateFlagsOptions, inboxId: UUID? = nil, apiConfiguration: mailslurpAPIConfiguration = mailslurpAPIConfiguration.shared) -> RequestBuilder<Void> {
        let localVariablePath = "/imap/server/update-flags"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: imapUpdateFlagsOptions, codableHelper: apiConfiguration.codableHelper)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "inboxId": (wrappedValue: inboxId?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
