//
// InboxRulesetControllerAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
@preconcurrency import PromiseKit

@objcMembers open class InboxRulesetControllerAPI : NSObject {

    /**
     Create an inbox ruleset
     
     - parameter createInboxRulesetOptions: (body)  
     - parameter inboxId: (query) Inbox id to attach ruleset to (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Promise<InboxRulesetDto>
     */
    open class func createNewInboxRuleset(createInboxRulesetOptions: CreateInboxRulesetOptions, inboxId: UUID? = nil, apiConfiguration: mailslurpAPIConfiguration = mailslurpAPIConfiguration.shared) -> Promise<InboxRulesetDto> {
        let deferred = Promise<InboxRulesetDto>.pending()
        createNewInboxRulesetWithRequestBuilder(createInboxRulesetOptions: createInboxRulesetOptions, inboxId: inboxId, apiConfiguration: apiConfiguration).execute { result in
            switch result {
            case let .success(response):
                deferred.resolver.fulfill(response.body)
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     Create an inbox ruleset
     - POST /rulesets
     - Create a new inbox rule for forwarding, blocking, and allowing emails when sending and receiving
     - API Key:
       - type: apiKey x-api-key (HEADER)
       - name: API_KEY
     - parameter createInboxRulesetOptions: (body)  
     - parameter inboxId: (query) Inbox id to attach ruleset to (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<InboxRulesetDto> 
     */
    open class func createNewInboxRulesetWithRequestBuilder(createInboxRulesetOptions: CreateInboxRulesetOptions, inboxId: UUID? = nil, apiConfiguration: mailslurpAPIConfiguration = mailslurpAPIConfiguration.shared) -> RequestBuilder<InboxRulesetDto> {
        let localVariablePath = "/rulesets"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createInboxRulesetOptions, codableHelper: apiConfiguration.codableHelper)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "inboxId": (wrappedValue: inboxId?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<InboxRulesetDto>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Delete an inbox ruleset
     
     - parameter _id: (path) ID of inbox ruleset 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Promise<Void>
     */
    open class func deleteInboxRuleset(_id: UUID, apiConfiguration: mailslurpAPIConfiguration = mailslurpAPIConfiguration.shared) -> Promise<Void> {
        let deferred = Promise<Void>.pending()
        deleteInboxRulesetWithRequestBuilder(_id: _id, apiConfiguration: apiConfiguration).execute { result in
            switch result {
            case .success:
                deferred.resolver.fulfill(())
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     Delete an inbox ruleset
     - DELETE /rulesets/{id}
     - Delete inbox ruleset
     - API Key:
       - type: apiKey x-api-key (HEADER)
       - name: API_KEY
     - parameter _id: (path) ID of inbox ruleset 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func deleteInboxRulesetWithRequestBuilder(_id: UUID, apiConfiguration: mailslurpAPIConfiguration = mailslurpAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/rulesets/{id}"
        let _idPreEscape = "\(APIHelper.mapValueToPathItem(_id))"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Delete inbox rulesets
     
     - parameter inboxId: (query) Optional inbox id to attach ruleset to (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Promise<Void>
     */
    open class func deleteInboxRulesets(inboxId: UUID? = nil, apiConfiguration: mailslurpAPIConfiguration = mailslurpAPIConfiguration.shared) -> Promise<Void> {
        let deferred = Promise<Void>.pending()
        deleteInboxRulesetsWithRequestBuilder(inboxId: inboxId, apiConfiguration: apiConfiguration).execute { result in
            switch result {
            case .success:
                deferred.resolver.fulfill(())
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     Delete inbox rulesets
     - DELETE /rulesets
     - Delete inbox rulesets. Accepts optional inboxId filter.
     - API Key:
       - type: apiKey x-api-key (HEADER)
       - name: API_KEY
     - parameter inboxId: (query) Optional inbox id to attach ruleset to (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func deleteInboxRulesetsWithRequestBuilder(inboxId: UUID? = nil, apiConfiguration: mailslurpAPIConfiguration = mailslurpAPIConfiguration.shared) -> RequestBuilder<Void> {
        let localVariablePath = "/rulesets"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "inboxId": (wrappedValue: inboxId?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Get an inbox ruleset
     
     - parameter _id: (path) ID of inbox ruleset 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Promise<InboxRulesetDto>
     */
    open class func getInboxRuleset(_id: UUID, apiConfiguration: mailslurpAPIConfiguration = mailslurpAPIConfiguration.shared) -> Promise<InboxRulesetDto> {
        let deferred = Promise<InboxRulesetDto>.pending()
        getInboxRulesetWithRequestBuilder(_id: _id, apiConfiguration: apiConfiguration).execute { result in
            switch result {
            case let .success(response):
                deferred.resolver.fulfill(response.body)
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     Get an inbox ruleset
     - GET /rulesets/{id}
     - Get inbox ruleset
     - API Key:
       - type: apiKey x-api-key (HEADER)
       - name: API_KEY
     - parameter _id: (path) ID of inbox ruleset 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<InboxRulesetDto> 
     */
    open class func getInboxRulesetWithRequestBuilder(_id: UUID, apiConfiguration: mailslurpAPIConfiguration = mailslurpAPIConfiguration.shared) -> RequestBuilder<InboxRulesetDto> {
        var localVariablePath = "/rulesets/{id}"
        let _idPreEscape = "\(APIHelper.mapValueToPathItem(_id))"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<InboxRulesetDto>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     * enum for parameter sort
     */
    public enum Sort_getInboxRulesets: String, Sendable, CaseIterable {
        case asc = "ASC"
        case desc = "DESC"
    }

    /**
     List inbox rulesets
     
     - parameter inboxId: (query) Optional inbox id to get rulesets from (optional)
     - parameter page: (query) Optional page index in inbox ruleset list pagination (optional, default to 0)
     - parameter size: (query) Optional page size in inbox ruleset list pagination (optional, default to 20)
     - parameter sort: (query) Optional createdAt sort direction ASC or DESC (optional, default to .asc)
     - parameter searchFilter: (query) Optional search filter (optional)
     - parameter since: (query) Filter by created at after the given timestamp (optional)
     - parameter before: (query) Filter by created at before the given timestamp (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Promise<PageInboxRulesetDto>
     */
    open class func getInboxRulesets(inboxId: UUID? = nil, page: Int? = nil, size: Int? = nil, sort: Sort_getInboxRulesets? = nil, searchFilter: String? = nil, since: Date? = nil, before: Date? = nil, apiConfiguration: mailslurpAPIConfiguration = mailslurpAPIConfiguration.shared) -> Promise<PageInboxRulesetDto> {
        let deferred = Promise<PageInboxRulesetDto>.pending()
        getInboxRulesetsWithRequestBuilder(inboxId: inboxId, page: page, size: size, sort: sort, searchFilter: searchFilter, since: since, before: before, apiConfiguration: apiConfiguration).execute { result in
            switch result {
            case let .success(response):
                deferred.resolver.fulfill(response.body)
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     List inbox rulesets
     - GET /rulesets
     - List all rulesets attached to an inbox
     - API Key:
       - type: apiKey x-api-key (HEADER)
       - name: API_KEY
     - parameter inboxId: (query) Optional inbox id to get rulesets from (optional)
     - parameter page: (query) Optional page index in inbox ruleset list pagination (optional, default to 0)
     - parameter size: (query) Optional page size in inbox ruleset list pagination (optional, default to 20)
     - parameter sort: (query) Optional createdAt sort direction ASC or DESC (optional, default to .asc)
     - parameter searchFilter: (query) Optional search filter (optional)
     - parameter since: (query) Filter by created at after the given timestamp (optional)
     - parameter before: (query) Filter by created at before the given timestamp (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<PageInboxRulesetDto> 
     */
    open class func getInboxRulesetsWithRequestBuilder(inboxId: UUID? = nil, page: Int? = nil, size: Int? = nil, sort: Sort_getInboxRulesets? = nil, searchFilter: String? = nil, since: Date? = nil, before: Date? = nil, apiConfiguration: mailslurpAPIConfiguration = mailslurpAPIConfiguration.shared) -> RequestBuilder<PageInboxRulesetDto> {
        let localVariablePath = "/rulesets"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "inboxId": (wrappedValue: inboxId?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "page": (wrappedValue: page?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "size": (wrappedValue: size?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "sort": (wrappedValue: sort?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "searchFilter": (wrappedValue: searchFilter?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "since": (wrappedValue: since?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "before": (wrappedValue: before?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PageInboxRulesetDto>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Test an inbox ruleset
     
     - parameter _id: (path) ID of inbox ruleset 
     - parameter inboxRulesetTestOptions: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Promise<InboxRulesetTestResult>
     */
    open class func testInboxRuleset(_id: UUID, inboxRulesetTestOptions: InboxRulesetTestOptions, apiConfiguration: mailslurpAPIConfiguration = mailslurpAPIConfiguration.shared) -> Promise<InboxRulesetTestResult> {
        let deferred = Promise<InboxRulesetTestResult>.pending()
        testInboxRulesetWithRequestBuilder(_id: _id, inboxRulesetTestOptions: inboxRulesetTestOptions, apiConfiguration: apiConfiguration).execute { result in
            switch result {
            case let .success(response):
                deferred.resolver.fulfill(response.body)
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     Test an inbox ruleset
     - POST /rulesets/{id}/test
     - Test an inbox ruleset
     - API Key:
       - type: apiKey x-api-key (HEADER)
       - name: API_KEY
     - parameter _id: (path) ID of inbox ruleset 
     - parameter inboxRulesetTestOptions: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<InboxRulesetTestResult> 
     */
    open class func testInboxRulesetWithRequestBuilder(_id: UUID, inboxRulesetTestOptions: InboxRulesetTestOptions, apiConfiguration: mailslurpAPIConfiguration = mailslurpAPIConfiguration.shared) -> RequestBuilder<InboxRulesetTestResult> {
        var localVariablePath = "/rulesets/{id}/test"
        let _idPreEscape = "\(APIHelper.mapValueToPathItem(_id))"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: inboxRulesetTestOptions, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<InboxRulesetTestResult>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Test receiving with inbox rulesets
     
     - parameter testInboxRulesetReceivingOptions: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Promise<TestInboxRulesetReceivingResult>
     */
    open class func testInboxRulesetReceiving(testInboxRulesetReceivingOptions: TestInboxRulesetReceivingOptions, apiConfiguration: mailslurpAPIConfiguration = mailslurpAPIConfiguration.shared) -> Promise<TestInboxRulesetReceivingResult> {
        let deferred = Promise<TestInboxRulesetReceivingResult>.pending()
        testInboxRulesetReceivingWithRequestBuilder(testInboxRulesetReceivingOptions: testInboxRulesetReceivingOptions, apiConfiguration: apiConfiguration).execute { result in
            switch result {
            case let .success(response):
                deferred.resolver.fulfill(response.body)
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     Test receiving with inbox rulesets
     - POST /rulesets/test-receiving
     - Test whether inbound emails from an email address would be blocked or allowed by inbox rulesets
     - API Key:
       - type: apiKey x-api-key (HEADER)
       - name: API_KEY
     - parameter testInboxRulesetReceivingOptions: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<TestInboxRulesetReceivingResult> 
     */
    open class func testInboxRulesetReceivingWithRequestBuilder(testInboxRulesetReceivingOptions: TestInboxRulesetReceivingOptions, apiConfiguration: mailslurpAPIConfiguration = mailslurpAPIConfiguration.shared) -> RequestBuilder<TestInboxRulesetReceivingResult> {
        let localVariablePath = "/rulesets/test-receiving"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: testInboxRulesetReceivingOptions, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<TestInboxRulesetReceivingResult>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Test sending with inbox rulesets
     
     - parameter testInboxRulesetSendingOptions: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Promise<TestInboxRulesetSendingResult>
     */
    open class func testInboxRulesetSending(testInboxRulesetSendingOptions: TestInboxRulesetSendingOptions, apiConfiguration: mailslurpAPIConfiguration = mailslurpAPIConfiguration.shared) -> Promise<TestInboxRulesetSendingResult> {
        let deferred = Promise<TestInboxRulesetSendingResult>.pending()
        testInboxRulesetSendingWithRequestBuilder(testInboxRulesetSendingOptions: testInboxRulesetSendingOptions, apiConfiguration: apiConfiguration).execute { result in
            switch result {
            case let .success(response):
                deferred.resolver.fulfill(response.body)
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     Test sending with inbox rulesets
     - POST /rulesets/test-sending
     - Test whether outbound emails to an email address would be blocked or allowed by inbox rulesets
     - API Key:
       - type: apiKey x-api-key (HEADER)
       - name: API_KEY
     - parameter testInboxRulesetSendingOptions: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<TestInboxRulesetSendingResult> 
     */
    open class func testInboxRulesetSendingWithRequestBuilder(testInboxRulesetSendingOptions: TestInboxRulesetSendingOptions, apiConfiguration: mailslurpAPIConfiguration = mailslurpAPIConfiguration.shared) -> RequestBuilder<TestInboxRulesetSendingResult> {
        let localVariablePath = "/rulesets/test-sending"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: testInboxRulesetSendingOptions, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<TestInboxRulesetSendingResult>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Test inbox rulesets for inbox
     
     - parameter inboxId: (query) ID of inbox 
     - parameter inboxRulesetTestOptions: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Promise<InboxRulesetTestResult>
     */
    open class func testInboxRulesetsForInbox(inboxId: UUID, inboxRulesetTestOptions: InboxRulesetTestOptions, apiConfiguration: mailslurpAPIConfiguration = mailslurpAPIConfiguration.shared) -> Promise<InboxRulesetTestResult> {
        let deferred = Promise<InboxRulesetTestResult>.pending()
        testInboxRulesetsForInboxWithRequestBuilder(inboxId: inboxId, inboxRulesetTestOptions: inboxRulesetTestOptions, apiConfiguration: apiConfiguration).execute { result in
            switch result {
            case let .success(response):
                deferred.resolver.fulfill(response.body)
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     Test inbox rulesets for inbox
     - PUT /rulesets
     - Test inbox rulesets for inbox
     - API Key:
       - type: apiKey x-api-key (HEADER)
       - name: API_KEY
     - parameter inboxId: (query) ID of inbox 
     - parameter inboxRulesetTestOptions: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<InboxRulesetTestResult> 
     */
    open class func testInboxRulesetsForInboxWithRequestBuilder(inboxId: UUID, inboxRulesetTestOptions: InboxRulesetTestOptions, apiConfiguration: mailslurpAPIConfiguration = mailslurpAPIConfiguration.shared) -> RequestBuilder<InboxRulesetTestResult> {
        let localVariablePath = "/rulesets"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: inboxRulesetTestOptions, codableHelper: apiConfiguration.codableHelper)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "inboxId": (wrappedValue: inboxId.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<InboxRulesetTestResult>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Test new inbox ruleset
     
     - parameter testNewInboxRulesetOptions: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Promise<InboxRulesetTestResult>
     */
    open class func testNewInboxRuleset(testNewInboxRulesetOptions: TestNewInboxRulesetOptions, apiConfiguration: mailslurpAPIConfiguration = mailslurpAPIConfiguration.shared) -> Promise<InboxRulesetTestResult> {
        let deferred = Promise<InboxRulesetTestResult>.pending()
        testNewInboxRulesetWithRequestBuilder(testNewInboxRulesetOptions: testNewInboxRulesetOptions, apiConfiguration: apiConfiguration).execute { result in
            switch result {
            case let .success(response):
                deferred.resolver.fulfill(response.body)
            case let .failure(error):
                deferred.resolver.reject(error)
            }
        }
        return deferred.promise
    }

    /**
     Test new inbox ruleset
     - PATCH /rulesets
     - Test new inbox ruleset
     - API Key:
       - type: apiKey x-api-key (HEADER)
       - name: API_KEY
     - parameter testNewInboxRulesetOptions: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<InboxRulesetTestResult> 
     */
    open class func testNewInboxRulesetWithRequestBuilder(testNewInboxRulesetOptions: TestNewInboxRulesetOptions, apiConfiguration: mailslurpAPIConfiguration = mailslurpAPIConfiguration.shared) -> RequestBuilder<InboxRulesetTestResult> {
        let localVariablePath = "/rulesets"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: testNewInboxRulesetOptions, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<InboxRulesetTestResult>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
