//
// AITransformCreateOptions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

@objcMembers public class AITransformCreateOptions: NSObject, Codable, ParameterConvertible {

    public var name: String?
    public var conditions: [String]?
    public var instructions: [String]?
    public var outputSchema: StructuredOutputSchema?
    public var outputSchemaId: UUID?
    public var extractPrompt: String?

    public init(name: String? = nil, conditions: [String]? = nil, instructions: [String]? = nil, outputSchema: StructuredOutputSchema? = nil, outputSchemaId: UUID? = nil, extractPrompt: String? = nil) {
        self.name = name
        self.conditions = conditions
        self.instructions = instructions
        self.outputSchema = outputSchema
        self.outputSchemaId = outputSchemaId
        self.extractPrompt = extractPrompt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case conditions
        case instructions
        case outputSchema
        case outputSchemaId
        case extractPrompt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(conditions, forKey: .conditions)
        try container.encodeIfPresent(instructions, forKey: .instructions)
        try container.encodeIfPresent(outputSchema, forKey: .outputSchema)
        try container.encodeIfPresent(outputSchemaId, forKey: .outputSchemaId)
        try container.encodeIfPresent(extractPrompt, forKey: .extractPrompt)
    }
}

