//
// AliasThreadProjection.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** A thread is a message thread created for a message received by an alias */
@objcMembers public class AliasThreadProjection: NSObject, Codable, ParameterConvertible {

    /** Thread subject */
    public var subject: String?
    /** Inbox ID */
    public var inboxId: UUID
    /** User ID */
    public var userId: UUID
    /** Updated at DateTime */
    public var updatedAt: Date
    /** Created at DateTime */
    public var createdAt: Date
    /** To recipients */
    public var to: [String]
    /** CC recipients */
    public var cc: [String]?
    /** BCC recipients */
    public var bcc: [String]?
    /** Alias ID */
    public var aliasId: UUID
    /** Name of thread */
    public var name: String?
    /** ID of email thread */
    public var _id: UUID

    public init(subject: String? = nil, inboxId: UUID, userId: UUID, updatedAt: Date, createdAt: Date, to: [String], cc: [String]? = nil, bcc: [String]? = nil, aliasId: UUID, name: String? = nil, _id: UUID) {
        self.subject = subject
        self.inboxId = inboxId
        self.userId = userId
        self.updatedAt = updatedAt
        self.createdAt = createdAt
        self.to = to
        self.cc = cc
        self.bcc = bcc
        self.aliasId = aliasId
        self.name = name
        self._id = _id
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case subject
        case inboxId
        case userId
        case updatedAt
        case createdAt
        case to
        case cc
        case bcc
        case aliasId
        case name
        case _id = "id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(subject, forKey: .subject)
        try container.encode(inboxId, forKey: .inboxId)
        try container.encode(userId, forKey: .userId)
        try container.encode(updatedAt, forKey: .updatedAt)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(to, forKey: .to)
        try container.encodeIfPresent(cc, forKey: .cc)
        try container.encodeIfPresent(bcc, forKey: .bcc)
        try container.encode(aliasId, forKey: .aliasId)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encode(_id, forKey: ._id)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension AliasThreadProjection: Identifiable {}
