//
// ConnectorSyncRequestResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

@objcMembers public class ConnectorSyncRequestResult: NSObject, Codable, ParameterConvertible {

    public var syncResult: ConnectorSyncResult?
    public var exception: String?
    public var eventId: UUID?

    public init(syncResult: ConnectorSyncResult? = nil, exception: String? = nil, eventId: UUID? = nil) {
        self.syncResult = syncResult
        self.exception = exception
        self.eventId = eventId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case syncResult
        case exception
        case eventId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(syncResult, forKey: .syncResult)
        try container.encodeIfPresent(exception, forKey: .exception)
        try container.encodeIfPresent(eventId, forKey: .eventId)
    }
}

