//
// GuestPortalUserDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

@objcMembers public class GuestPortalUserDto: NSObject, Codable, ParameterConvertible {

    public var _id: UUID
    public var userId: UUID
    public var portalId: UUID
    public var name: String?
    public var username: String
    public var emailAddress: String?
    public var inboxId: UUID?
    public var loginUrl: String
    public var createdAt: Date
    public var updatedAt: Date

    public init(_id: UUID, userId: UUID, portalId: UUID, name: String? = nil, username: String, emailAddress: String? = nil, inboxId: UUID? = nil, loginUrl: String, createdAt: Date, updatedAt: Date) {
        self._id = _id
        self.userId = userId
        self.portalId = portalId
        self.name = name
        self.username = username
        self.emailAddress = emailAddress
        self.inboxId = inboxId
        self.loginUrl = loginUrl
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case _id = "id"
        case userId
        case portalId
        case name
        case username
        case emailAddress
        case inboxId
        case loginUrl
        case createdAt
        case updatedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(_id, forKey: ._id)
        try container.encode(userId, forKey: .userId)
        try container.encode(portalId, forKey: .portalId)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encode(username, forKey: .username)
        try container.encodeIfPresent(emailAddress, forKey: .emailAddress)
        try container.encodeIfPresent(inboxId, forKey: .inboxId)
        try container.encode(loginUrl, forKey: .loginUrl)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension GuestPortalUserDto: Identifiable {}
