//
// InboxReplierEventProjection.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Inbox replier event */
@objc public class InboxReplierEventProjection: NSObject, Codable, JSONEncodable {

    public enum Status: String, Codable, CaseIterable {
        case success = "SUCCESS"
        case failure = "FAILURE"
    }
    public var recipients: [String]?
    public var userId: UUID?
    public var emailId: UUID?
    public var inboxId: UUID?
    public var sentId: UUID?
    public var replierId: UUID?
    public var createdAt: Date
    public var message: String?
    public var _id: UUID?
    public var status: Status?

    public init(recipients: [String]? = nil, userId: UUID? = nil, emailId: UUID? = nil, inboxId: UUID? = nil, sentId: UUID? = nil, replierId: UUID? = nil, createdAt: Date, message: String? = nil, _id: UUID? = nil, status: Status? = nil) {
        self.recipients = recipients
        self.userId = userId
        self.emailId = emailId
        self.inboxId = inboxId
        self.sentId = sentId
        self.replierId = replierId
        self.createdAt = createdAt
        self.message = message
        self._id = _id
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case recipients
        case userId
        case emailId
        case inboxId
        case sentId
        case replierId
        case createdAt
        case message
        case _id = "id"
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(recipients, forKey: .recipients)
        try container.encodeIfPresent(userId, forKey: .userId)
        try container.encodeIfPresent(emailId, forKey: .emailId)
        try container.encodeIfPresent(inboxId, forKey: .inboxId)
        try container.encodeIfPresent(sentId, forKey: .sentId)
        try container.encodeIfPresent(replierId, forKey: .replierId)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(message, forKey: .message)
        try container.encodeIfPresent(_id, forKey: ._id)
        try container.encodeIfPresent(status, forKey: .status)
    }
}

