//
// PhonePlanAvailabilityItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

@objcMembers public class PhonePlanAvailabilityItem: NSObject, Codable, ParameterConvertible {

    public enum PhoneCountry: String, Sendable, Codable, CaseIterable {
        case us = "US"
        case gb = "GB"
        case au = "AU"
        case ca = "CA"
        case ee = "EE"
        case hk = "HK"
        case pl = "PL"
        case ch = "CH"
        case pt = "PT"
        case nl = "NL"
        case il = "IL"
        case se = "SE"
    }
    public enum AvailabilityStatus: String, Sendable, Codable, CaseIterable {
        case available = "AVAILABLE"
        case nonMatchingSubscriptionCurrency = "NON_MATCHING_SUBSCRIPTION_CURRENCY"
        case nonMatchingSubscriptionType = "NON_MATCHING_SUBSCRIPTION_TYPE"
        case alreadyAssigned = "ALREADY_ASSIGNED"
    }
    public var phoneCountry: PhoneCountry
    public var availabilityStatus: AvailabilityStatus

    public init(phoneCountry: PhoneCountry, availabilityStatus: AvailabilityStatus) {
        self.phoneCountry = phoneCountry
        self.availabilityStatus = availabilityStatus
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case phoneCountry
        case availabilityStatus
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(phoneCountry, forKey: .phoneCountry)
        try container.encode(availabilityStatus, forKey: .availabilityStatus)
    }
}

