//
// SentEmailProjection.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@objc public class SentEmailProjection: NSObject, Codable, JSONEncodable {

    public var createdAt: Date
    public var _id: UUID
    public var bodyMD5Hash: String?
    public var userId: UUID
    public var from: String?
    public var subject: String?
    public var inboxId: UUID
    public var attachments: [String]
    public var to: [String]
    public var bcc: [String]
    public var cc: [String]
    public var virtualSend: Bool

    public init(createdAt: Date, _id: UUID, bodyMD5Hash: String? = nil, userId: UUID, from: String? = nil, subject: String? = nil, inboxId: UUID, attachments: [String], to: [String], bcc: [String], cc: [String], virtualSend: Bool) {
        self.createdAt = createdAt
        self._id = _id
        self.bodyMD5Hash = bodyMD5Hash
        self.userId = userId
        self.from = from
        self.subject = subject
        self.inboxId = inboxId
        self.attachments = attachments
        self.to = to
        self.bcc = bcc
        self.cc = cc
        self.virtualSend = virtualSend
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case createdAt
        case _id = "id"
        case bodyMD5Hash
        case userId
        case from
        case subject
        case inboxId
        case attachments
        case to
        case bcc
        case cc
        case virtualSend
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(_id, forKey: ._id)
        try container.encodeIfPresent(bodyMD5Hash, forKey: .bodyMD5Hash)
        try container.encode(userId, forKey: .userId)
        try container.encodeIfPresent(from, forKey: .from)
        try container.encodeIfPresent(subject, forKey: .subject)
        try container.encode(inboxId, forKey: .inboxId)
        try container.encode(attachments, forKey: .attachments)
        try container.encode(to, forKey: .to)
        try container.encode(bcc, forKey: .bcc)
        try container.encode(cc, forKey: .cc)
        try container.encode(virtualSend, forKey: .virtualSend)
    }
}

