//
// Sort.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct Sort: Codable, Hashable {

    public var empty: Bool?
    public var sorted: Bool?
    public var unsorted: Bool?

    public init(empty: Bool? = nil, sorted: Bool? = nil, unsorted: Bool? = nil) {
        self.empty = empty
        self.sorted = sorted
        self.unsorted = unsorted
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case empty
        case sorted
        case unsorted
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(empty, forKey: .empty)
        try container.encodeIfPresent(sorted, forKey: .sorted)
        try container.encodeIfPresent(unsorted, forKey: .unsorted)
    }



}
