//
// TemplateProjection.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

/** Email template data */
public struct TemplateProjection: Codable, Hashable {

    public var name: String
    public var id: UUID
    public var createdAt: Date
    public var updatedAt: Date
    public var variables: [String]

    public init(name: String, id: UUID, createdAt: Date, updatedAt: Date, variables: [String]) {
        self.name = name
        self.id = id
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.variables = variables
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case id
        case createdAt
        case updatedAt
        case variables
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(id, forKey: .id)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
        try container.encode(variables, forKey: .variables)
    }



}
