//
// TotpDeviceOptionalDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

@objcMembers public class TotpDeviceOptionalDto: NSObject, Codable, ParameterConvertible {

    public var device: TotpDeviceDto?

    public init(device: TotpDeviceDto? = nil) {
        self.device = device
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case device
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(device, forKey: .device)
    }
}

