//
// UnknownMissedEmailProjection.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Unknown missed email projection */
@objcMembers public class UnknownMissedEmailProjection: NSObject, Codable, ParameterConvertible {

    public var subject: String?
    public var createdAt: Date
    public var to: [String]?
    public var _id: UUID
    public var from: String?

    public init(subject: String? = nil, createdAt: Date, to: [String]? = nil, _id: UUID, from: String? = nil) {
        self.subject = subject
        self.createdAt = createdAt
        self.to = to
        self._id = _id
        self.from = from
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case subject
        case createdAt
        case to
        case _id = "id"
        case from
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(subject, forKey: .subject)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(to, forKey: .to)
        try container.encode(_id, forKey: ._id)
        try container.encodeIfPresent(from, forKey: .from)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension UnknownMissedEmailProjection: Identifiable {}
